<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FParsec" Version="1.1.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Token.fs" />
    <Compile Include="Lexer.fs" />
    <Compile Include="AST.fs" />
    <Compile Include="Parser.fs" />
    <Compile Include="FParsecParser.fs" />
    <Compile Include="Elaborator.fs" />
    <Compile Include="Types.fs" />
    <Compile Include="TypedAST.fs" />
    <Compile Include="HMInfer.fs" />
    <Compile Include="Platform.fs" />
    <Compile Include="Codegen.fs" />
    <Compile Include="CodegenTS.fs" />
    <Compile Include="CodegenPy.fs" />
    <Compile Include="CodegenJava.fs" />
    <Compile Include="CodegenCSharp.fs" />
    <Compile Include="CodegenLLVM.fs" />
    <Compile Include="ReverseTranspiler.fs" />
    <Compile Include="Manifest.fs" />
    <Compile Include="ProjectLoader.fs" />
    <Compile Include="Compiler.fs" />
  </ItemGroup>
</Project>
