module LLLang.Tests.CodegenTSTests

open Xunit
open LLLang.Compiler

// ---------- helpers ----------

let private tsSrc (src: string) : string =
    match compileToTS src with
    | Ok ts -> ts
    | Error es -> failwith $"TS codegen failed: {es}"

// ---------- type declarations ----------

[<Fact>]
let ``TS: sum type emits discriminated union interface`` () =
    let src = "module M\nShape = Circle Float | Rect Float Float | Empty"
    let ts = tsSrc src
    Assert.Contains("_tag:", ts)
    Assert.Contains("Circle", ts)
    Assert.Contains("Rect", ts)
    Assert.Contains("Empty", ts)

[<Fact>]
let ``TS: sum type emits union type alias`` () =
    let src = "module M\nShape = Circle Float | Rect Float Float | Empty"
    Assert.Contains("type Shape =", tsSrc src)

[<Fact>]
let ``TS: zero-arg constructor emits const`` () =
    let src = "module M\nShape = Circle Float | Empty"
    let ts = tsSrc src
    Assert.Contains("const Empty", ts)
    Assert.Contains("as const", ts)

[<Fact>]
let ``TS: generic zero-arg constructor does not emit free type variable`` () =
    let src = "module M\nMaybe A = Some A | None"
    let ts = tsSrc src
    Assert.Contains("const None: Maybe<unknown>", ts)
    Assert.DoesNotContain("const None: Maybe<A>", ts)

[<Fact>]
let ``TS: generated public surface avoids any`` () =
    let src = "module M\nMaybe A = Some A | None\nid(x A) A = x\n"
    let ts = tsSrc src
    Assert.DoesNotContain(": any", ts)
    Assert.DoesNotContain("<any>", ts)

[<Fact>]
let ``TS: maybeWithDefault builtin is lowered to typed helper`` () =
    let src = "module M\nMaybe A = Some A | None\nf(m Maybe[Int]) Int = maybeWithDefault 0 m\n"
    let ts = tsSrc src
    Assert.Contains("m !== null ? m : d", ts)
    Assert.DoesNotContain("maybeWithDefault(", ts)

[<Fact>]
let ``TS: parametric type emits generic syntax`` () =
    let src = "module M\nMaybe A = Some A | None"
    let ts = tsSrc src
    Assert.Contains("<A>", ts)

[<Fact>]
let ``TS: Int maps to number`` () =
    let src = "module M\nid(x Int) Int = x"
    let ts = tsSrc src
    Assert.Contains("number", ts)

[<Fact>]
let ``TS: Str maps to string`` () =
    let src = "module M\ngreet(s Str) Str = s"
    let ts = tsSrc src
    Assert.Contains("string", ts)

[<Fact>]
let ``TS: Bool maps to boolean`` () =
    let src = "module M\nneg(b Bool) Bool = !b"
    let ts = tsSrc src
    Assert.Contains("boolean", ts)

// ---------- function declarations ----------

[<Fact>]
let ``TS: simple fn emits arrow function`` () =
    let src = "module M\nadd(a Int)(b Int) Int = a + b"
    let ts = tsSrc src
    Assert.Contains("const add", ts)
    Assert.Contains("=>", ts)

[<Fact>]
let ``TS: curried fn nests arrow functions`` () =
    let src = "module M\nadd(a Int)(b Int) Int = a + b"
    let ts = tsSrc src
    // Two levels of currying
    let arrowCount = ts.Split([|"=>"|], System.StringSplitOptions.None).Length - 1
    Assert.True(arrowCount >= 2, $"expected >= 2 arrows; got:\n{ts}")

[<Fact>]
let ``TS: let binding emits const`` () =
    let src = "module M\nlet x = 42"
    let ts = tsSrc src
    Assert.Contains("const x", ts)
    Assert.Contains("42", ts)

[<Fact>]
let ``TS: if-then-else emits ternary`` () =
    let src = "module M\nabs(x Int) Int =\n  if x > 0\n    x\n  else 0 - x"
    let ts = tsSrc src
    Assert.Contains("?", ts)

[<Fact>]
let ``TS: strConcat emits plus`` () =
    let src = "module M\ngreet(name Str) Str = strConcat \"Hello \" name"
    let ts = tsSrc src
    Assert.Contains("+", ts)

[<Fact>]
let ``TS: list type emits array syntax`` () =
    let src = "module M\nlen(xs List[Int]) Int = listLen xs"
    let ts = tsSrc src
    Assert.Contains("number[]", ts)

[<Fact>]
let ``TS: emits header comment`` () =
    let src = "module M\nlet x = 1"
    let ts = tsSrc src
    Assert.Contains("Generated by lllc", ts)

[<Fact>]
let ``TS: stdlib block is omitted when stdlib symbols are unused`` () =
    let src = "module M\nlet x = 1"
    let ts = tsSrc src
    Assert.DoesNotContain("// --- ll-lang stdlib (TypeScript) ---", ts)
    Assert.DoesNotContain("const listLen =", ts)

[<Fact>]
let ``TS: stdlib helper is emitted once and reused`` () =
    let src =
        "module M\n" +
        "f(xs List[Int]) Int = listLen xs + listLen xs\n"
    let ts = tsSrc src
    let helperCount = ts.Split([|"const listLen ="|], System.StringSplitOptions.None).Length - 1
    Assert.Equal(1, helperCount)
    let callCount = ts.Split([|"(listLen)(xs)"|], System.StringSplitOptions.None).Length - 1
    Assert.Equal(2, callCount)

[<Fact>]
let ``TS: external console_log emits console.log mapping`` () =
    let src =
        "module M\n" +
        "external console_log(msg Str) Unit\n" +
        "main() = console_log \"hi\"\n"
    let ts = tsSrc src
    Assert.Contains("const console_log = (msg: string) => console.log(msg);", ts)

[<Fact>]
let ``TS: external JSON_parse and fetch emit native mapping`` () =
    let src =
        "module M\n" +
        "opaque Any\n" +
        "opaque Response\n" +
        "opaque Promise[A]\n" +
        "external JSON_parse(s Str) Any\n" +
        "external fetch(url Str) Promise[Response]\n" +
        "let raw = JSON_parse \"{}\"\n" +
        "let req = fetch \"https://example.com\"\n"
    let ts = tsSrc src
    Assert.Contains("const JSON_parse = (s: string) => JSON.parse(s);", ts)
    Assert.Contains("const fetch = (url: string) => (globalThis as any).fetch(url);", ts)

[<Fact>]
let ``TS: char zero escapes as slash-zero literal`` () =
    let src = "module M\nlet c = '\\0'"
    let ts = tsSrc src
    Assert.Contains("`\\0`", ts)
    Assert.DoesNotContain(0uy, System.Text.Encoding.UTF8.GetBytes(ts))

// ---------- pattern matching ----------

[<Fact>]
let ``TS: match on sum type checks _tag`` () =
    let src = "module M\nColor = Red | Green | Blue\ntoInt(c Color) Int = match c | Red -> 0 | Green -> 1 | Blue -> 2"
    let ts = tsSrc src
    Assert.Contains("_tag", ts)

[<Fact>]
let ``TS: match emits conditional expression`` () =
    let src = "module M\nColor = Red | Green\ntoInt(c Color) Int = match c | Red -> 0 | Green -> 1"
    let ts = tsSrc src
    Assert.Contains("Red", ts)
    Assert.Contains("Green", ts)

// ---------- round-trip via compileTarget ----------

[<Fact>]
let ``compileTarget TypeScript produces same as compileToTS`` () =
    let src = "module M\nid(x Int) Int = x"
    let a = compileToTS src
    let b = compileTarget TypeScript src
    Assert.Equal(a, b)

[<Fact>]
let ``compileTarget FSharp produces F# not TS`` () =
    let src = "module M\nid(x Int) Int = x"
    match compileTarget FSharp src with
    | Ok fs ->
        Assert.Contains("let", fs)
        Assert.DoesNotContain("const", fs)
    | Error es -> failwith $"unexpected error: {es}"
