module LLLang.Tests.CodegenJavaTests

open Xunit
open LLLang.Compiler

// ---------- helpers ----------

let private javaSrc (src: string) : string =
    match compileToJava src with
    | Ok java -> java
    | Error es -> failwith $"Java codegen failed: {es}"

// ---------- basic output ----------

[<Fact>]
let ``Java: compileToJava produces non-empty output for trivial module`` () =
    let src = "module M\nlet x = 42"
    let java = javaSrc src
    Assert.False(System.String.IsNullOrWhiteSpace(java))

[<Fact>]
let ``Java: header contains Generated by lllc`` () =
    let src = "module M\nlet x = 1"
    let java = javaSrc src
    Assert.Contains("Generated by lllc", java)

[<Fact>]
let ``Java: imports at top`` () =
    let src = "module M\nlet x = 1"
    let java = javaSrc src
    Assert.Contains("import java.util.List;", java)
    Assert.Contains("import java.util.Optional;", java)
    Assert.Contains("import java.util.function.Function;", java)

[<Fact>]
let ``Java: class wrapper present`` () =
    let src = "module M\nlet x = 1"
    let java = javaSrc src
    Assert.Contains("public class", java)

// ---------- type mappings ----------

[<Fact>]
let ``Java: Int maps to long`` () =
    let src = "module M\nfn id(x Int) Int = x"
    let java = javaSrc src
    Assert.Contains("long", java)

[<Fact>]
let ``Java: Str maps to String`` () =
    let src = "module M\nfn greet(s Str) Str = s"
    let java = javaSrc src
    Assert.Contains("String", java)

[<Fact>]
let ``Java: Bool maps to boolean`` () =
    let src = "module M\nfn neg(b Bool) Bool = !b"
    let java = javaSrc src
    Assert.Contains("boolean", java)

[<Fact>]
let ``Java: Float maps to double`` () =
    let src = "module M\nfn sq(x Float) Float = x * x"
    let java = javaSrc src
    Assert.Contains("double", java)

// ---------- type declarations ----------

[<Fact>]
let ``Java: sum type emits sealed interface`` () =
    let src = "module M\ntype Shape = Circle Float | Rect Float Float | Empty"
    let java = javaSrc src
    Assert.Contains("sealed interface Shape", java)

[<Fact>]
let ``Java: sum type constructors emit as records`` () =
    let src = "module M\ntype Shape = Circle Float | Rect Float Float | Empty"
    let java = javaSrc src
    Assert.Contains("record Circle", java)
    Assert.Contains("record Rect", java)
    Assert.Contains("record Empty", java)

[<Fact>]
let ``Java: constructor fields have correct Java types`` () =
    let src = "module M\ntype Shape = Circle Float | Point Int Int"
    let java = javaSrc src
    Assert.Contains("Double _0", java)
    Assert.Contains("Long _0", java)

[<Fact>]
let ``Java: sum type permits clause lists constructors`` () =
    let src = "module M\ntype Color = Red | Green | Blue"
    let java = javaSrc src
    Assert.Contains("permits", java)

[<Fact>]
let ``Java: parametric type emits generics`` () =
    let src = "module M\ntype Maybe A = Some A | None"
    let java = javaSrc src
    Assert.Contains("<A>", java)

// ---------- function declarations ----------

[<Fact>]
let ``Java: simple fn emits public static`` () =
    let src = "module M\nfn double(x Int) Int = x * 2"
    let java = javaSrc src
    Assert.Contains("public static", java)
    Assert.Contains("double_", java)  // 'double' is a Java keyword, becomes 'double_'

[<Fact>]
let ``Java: single-param fn includes return`` () =
    let src = "module M\nfn id(x Int) Int = x"
    let java = javaSrc src
    Assert.Contains("return", java)

[<Fact>]
let ``Java: curried fn emits Function return type`` () =
    let src = "module M\nfn add(a Int)(b Int) Int = a + b"
    let java = javaSrc src
    Assert.Contains("Function", java)

[<Fact>]
let ``Java: int literal has L suffix`` () =
    let src = "module M\nlet x = 42"
    let java = javaSrc src
    Assert.Contains("42L", java)

// ---------- let bindings ----------

[<Fact>]
let ``Java: let binding emits public static final`` () =
    let src = "module M\nlet x = 42"
    let java = javaSrc src
    Assert.Contains("public static final", java)

[<Fact>]
let ``Java: let binding has correct name`` () =
    let src = "module M\nlet answer = 42"
    let java = javaSrc src
    Assert.Contains("answer", java)

// ---------- main function ----------

[<Fact>]
let ``Java: main fn emits public static void main`` () =
    let src = "module M\nfn main() Unit = printfn \"hello\""
    let java = javaSrc src
    Assert.Contains("public static void main(String[] args)", java)

// ---------- if-then-else ----------

[<Fact>]
let ``Java: if-then-else emits ternary`` () =
    let src = "module M\nfn abs(x Int) Int =\n  if x > 0\n    x\n  else 0 - x"
    let java = javaSrc src
    Assert.Contains("?", java)
    Assert.Contains(":", java)

// ---------- arithmetic ----------

[<Fact>]
let ``Java: arithmetic uses standard operators`` () =
    let src = "module M\nfn add(a Int)(b Int) Int = a + b"
    let java = javaSrc src
    Assert.Contains("+", java)

// ---------- compileTarget round-trip ----------

[<Fact>]
let ``compileTarget Java produces same as compileToJava`` () =
    let src = "module M\nfn id(x Int) Int = x"
    let a = compileToJava src
    let b = compileTarget Java src
    Assert.Equal(a, b)

[<Fact>]
let ``compileTarget Java does not emit F# let keyword`` () =
    let src = "module M\nfn id(x Int) Int = x"
    match compileTarget Java src with
    | Ok java ->
        Assert.DoesNotContain("\nlet id", java)
    | Error es -> failwith $"unexpected error: {es}"

[<Fact>]
let ``compileTarget Java does not emit TypeScript syntax`` () =
    let src = "module M\nfn id(x Int) Int = x"
    match compileTarget Java src with
    | Ok java ->
        Assert.DoesNotContain("const ", java)
    | Error es -> failwith $"unexpected error: {es}"
