module LLLang.Tests.CodegenJavaTests

open System
open System.IO
open System.Diagnostics
open Xunit
open LLLang.Elaborator
open LLLang.Compiler

// ---------- helpers ----------

let private javaSrc (src: string) : string =
    match compileToJava src with
    | Ok java -> java
    | Error es -> failwith $"Java codegen failed: {es}"

let private runProc (cwd: string) (exe: string) (args: string list) : int * string * string =
    let psi = ProcessStartInfo(exe)
    psi.WorkingDirectory <- cwd
    psi.UseShellExecute <- false
    psi.RedirectStandardOutput <- true
    psi.RedirectStandardError <- true
    for arg in args do
        psi.ArgumentList.Add(arg)
    use proc = LLLang.Tests.TestCompat.startProcess psi
    let stdout = proc.StandardOutput.ReadToEnd()
    let stderr = proc.StandardError.ReadToEnd()
    proc.WaitForExit()
    (proc.ExitCode, stdout, stderr)

let private toolExists (exe: string) : bool =
    let (code, _, _) = runProc __SOURCE_DIRECTORY__ "sh" ["-lc"; "command -v " + exe + " >/dev/null 2>&1"]
    code = 0

// ---------- basic output ----------

[<Fact>]
let ``Java: compileToJava produces non-empty output for trivial module`` () =
    let src = "module M\nlet x = 42"
    let java = javaSrc src
    Assert.False(System.String.IsNullOrWhiteSpace(java))

[<Fact>]
let ``Java: header contains Generated by lllc`` () =
    let src = "module M\nlet x = 1"
    let java = javaSrc src
    Assert.Contains("Generated by lllc", java)

[<Fact>]
let ``Java: imports at top`` () =
    let src = "module M\nlet x = 1"
    let java = javaSrc src
    Assert.Contains("import java.util.List;", java)
    Assert.Contains("import java.util.Optional;", java)
    Assert.Contains("import java.util.function.Function;", java)

[<Fact>]
let ``Java: class wrapper present`` () =
    let src = "module M\nlet x = 1"
    let java = javaSrc src
    Assert.Contains("public class", java)

// ---------- type mappings ----------

[<Fact>]
let ``Java: Int maps to long`` () =
    let src = "module M\nid(x Int) Int = x"
    let java = javaSrc src
    Assert.Contains("long", java)

[<Fact>]
let ``Java: Str maps to String`` () =
    let src = "module M\ngreet(s Str) Str = s"
    let java = javaSrc src
    Assert.Contains("String", java)

[<Fact>]
let ``Java: Bool maps to boolean`` () =
    let src = "module M\nneg(b Bool) Bool = !b"
    let java = javaSrc src
    Assert.Contains("boolean", java)

[<Fact>]
let ``Java: Float maps to double`` () =
    let src = "module M\nsq(x Float) Float = x * x"
    let java = javaSrc src
    Assert.Contains("double", java)

// ---------- type declarations ----------

[<Fact>]
let ``Java: sum type emits sealed interface`` () =
    let src = "module M\nShape = Circle Float | Rect Float Float | Empty"
    let java = javaSrc src
    Assert.Contains("sealed interface Shape", java)

[<Fact>]
let ``Java: sum type constructors emit as records`` () =
    let src = "module M\nShape = Circle Float | Rect Float Float | Empty"
    let java = javaSrc src
    Assert.Contains("record Circle", java)
    Assert.Contains("record Rect", java)
    Assert.Contains("record Empty", java)

[<Fact>]
let ``Java: constructor fields have correct Java types`` () =
    let src = "module M\nShape = Circle Float | Point Int Int"
    let java = javaSrc src
    Assert.Contains("Double _0", java)
    Assert.Contains("Long _0", java)

[<Fact>]
let ``Java: sum type permits clause lists constructors`` () =
    let src = "module M\nColor = Red | Green | Blue"
    let java = javaSrc src
    Assert.Contains("permits", java)

[<Fact>]
let ``Java: parametric type emits generics`` () =
    let src = "module M\nMaybe A = Some A | None"
    let java = javaSrc src
    Assert.Contains("<A>", java)

[<Fact>]
let ``Java: nested type application emits single generic argument list`` () =
    let src = "module M\nid(x Result[Int][Str]) Result[Int][Str] = x"
    let java = javaSrc src
    Assert.Contains("Result<Long, String>", java)
    Assert.DoesNotContain("><", java)

[<Fact>]
let ``Java: generic signatures use imported List and Optional types`` () =
    let src = "module M\nidList(xs List[Int]) List[Int] = xs\nidMaybe(m Maybe[Int]) Maybe[Int] = m"
    let java = javaSrc src
    Assert.Contains("List<Long>", java)
    Assert.Contains("Optional<Long>", java)
    Assert.DoesNotContain("java.util.List<", java)
    Assert.DoesNotContain("java.util.Optional<", java)

// ---------- function declarations ----------

[<Fact>]
let ``Java: simple fn emits public static`` () =
    let src = "module M\ndouble(x Int) Int = x * 2"
    let java = javaSrc src
    Assert.Contains("public static", java)
    Assert.Contains("double_", java)  // 'double' is a Java keyword, becomes 'double_'

[<Fact>]
let ``Java: single-param fn includes return`` () =
    let src = "module M\nid(x Int) Int = x"
    let java = javaSrc src
    Assert.Contains("return", java)

[<Fact>]
let ``Java: curried fn emits Function return type`` () =
    let src = "module M\nadd(a Int)(b Int) Int = a + b"
    let java = javaSrc src
    Assert.Contains("Function", java)
    Assert.DoesNotContain("java.util.function.Function<", java)

[<Fact>]
let ``Java: int literal has L suffix`` () =
    let src = "module M\nlet x = 42"
    let java = javaSrc src
    Assert.Contains("42L", java)

// ---------- let bindings ----------

[<Fact>]
let ``Java: let binding emits public static final`` () =
    let src = "module M\nlet x = 42"
    let java = javaSrc src
    Assert.Contains("public static final", java)

[<Fact>]
let ``Java: let binding has correct name`` () =
    let src = "module M\nlet answer = 42"
    let java = javaSrc src
    Assert.Contains("answer", java)

// ---------- main function ----------

[<Fact>]
let ``Java: main fn emits public static void main`` () =
    let src = "module M\nmain() Unit = printfn \"hello\""
    let java = javaSrc src
    Assert.Contains("public static void main(String[] args)", java)

[<Fact>]
let ``Java: main sequencing preserves side effects at runtime`` () =
    if not (toolExists "javac") || not (toolExists "java") then
        ()
    else
        let src =
            "module Smoke\n"
            + "main() Int =\n"
            + "  _ = printfn \"smoke\"\n"
            + "  0\n"
        let java = javaSrc src
        let tempRoot = Path.Combine(Path.GetTempPath(), "lll-java-main-smoke-" + Guid.NewGuid().ToString("N"))
        Directory.CreateDirectory(tempRoot) |> ignore
        try
            let javaPath = Path.Combine(tempRoot, "Smoke.java")
            File.WriteAllText(javaPath, java)
            let (compileCode, compileOut, compileErr) = runProc tempRoot "javac" [javaPath]
            Assert.True((compileCode = 0), $"javac failed\nstdout:\n{compileOut}\nstderr:\n{compileErr}\nsource:\n{java}")

            let (runCode, runOut, runErr) = runProc tempRoot "java" ["-cp"; tempRoot; "Smoke"]
            Assert.True((runCode = 0), $"java run failed\nstdout:\n{runOut}\nstderr:\n{runErr}\nsource:\n{java}")
            Assert.Contains("smoke", runOut)
        finally
            try Directory.Delete(tempRoot, true) with _ -> ()

[<Fact>]
let ``Java: external console_log emits System.out.println`` () =
    let src = "module M\nexternal console_log(msg Str) Unit"
    let java = javaSrc src
    Assert.Contains("console_log(", java)
    Assert.Contains("System.out.println(msg)", java)

[<Fact>]
let ``Java: unknown external declaration raises E026`` () =
    let src = "module M\nexternal host_log(msg Str) Unit"
    match compileToJava src with
    | Ok java -> failwith $"unexpected success: {java}"
    | Error es ->
        let e = es |> List.exactlyOne
        Assert.Equal(E026, e.Code)
        Assert.Contains("UnknownExternalMapping", e.Message)
        Assert.Contains("target:java", e.Message)
        Assert.Contains("name:host_log", e.Message)

// ---------- if-then-else ----------

[<Fact>]
let ``Java: if-then-else emits ternary`` () =
    let src = "module M\nabs(x Int) Int =\n  if x > 0\n    x\n  else 0 - x"
    let java = javaSrc src
    Assert.Contains("?", java)
    Assert.Contains(":", java)

// ---------- arithmetic ----------

[<Fact>]
let ``Java: arithmetic uses standard operators`` () =
    let src = "module M\nadd(a Int)(b Int) Int = a + b"
    let java = javaSrc src
    Assert.Contains("+", java)

[<Fact>]
let ``Java: symbolic operators lower without raw symbolic identifiers`` () =
    let src =
        "module M\n"
        + "main() Int =\n"
        + "  x = 5 >>= (\\n. n + 1)\n"
        + "  y = x <|> 0\n"
        + "  z = y >> 7\n"
        + "  z\n"
    let java = javaSrc src
    Assert.DoesNotContain(">>=", java)
    Assert.DoesNotContain("<|>", java)
    Assert.DoesNotContain(" >> ", java)

[<Fact>]
let ``Java: prelude exposes maybeWithDefault builtin`` () =
    let src = "module M\nmain() Unit = printfn \"x\""
    let java = javaSrc src
    Assert.Contains("maybeWithDefault", java)

[<Fact>]
let ``Java: prelude helpers are omitted when stdlib is unused`` () =
    let src = "module M\nlet x = 1"
    let java = javaSrc src
    Assert.DoesNotContain("maybeWithDefault", java)
    Assert.DoesNotContain("listFold(", java)

[<Fact>]
let ``Java: generated stdlib and curried calls compile with javac`` () =
    if not (toolExists "javac") then
        ()
    else
        let src = "module Demo\nadd(x Int)(y Int) Int = x + y\nmain() Int = min (add 1 2) (abs 5)\n"
        let java = javaSrc src
        Assert.Contains("min_(", java)
        Assert.Contains("abs_(", java)
        Assert.Contains("add(", java)

        let tempRoot = Path.Combine(Path.GetTempPath(), "lll-java-codegen-" + Guid.NewGuid().ToString("N"))
        Directory.CreateDirectory(tempRoot) |> ignore
        try
            let javaPath = Path.Combine(tempRoot, "Demo.java")
            File.WriteAllText(javaPath, java)
            let (code, so, se) = runProc tempRoot "javac" [javaPath]
            Assert.True((code = 0), $"javac failed\nstdout:\n{so}\nstderr:\n{se}\nsource:\n{java}")
        finally
            try Directory.Delete(tempRoot, true) with _ -> ()

[<Fact>]
let ``Java: passing known static function as value emits callable lambda and compiles`` () =
    if not (toolExists "javac") then
        ()
    else
        let src =
            "module Demo\n"
            + "apply(f Int->Int)(x Int) Int = f x\n"
            + "double(x Int) Int = x * 2\n"
            + "main() Int = apply double 2\n"
        let java = javaSrc src
        Assert.Contains("__ll_arg -> double_(__ll_arg)", java)

        let tempRoot = Path.Combine(Path.GetTempPath(), "lll-java-fn-value-" + Guid.NewGuid().ToString("N"))
        Directory.CreateDirectory(tempRoot) |> ignore
        try
            let javaPath = Path.Combine(tempRoot, "Demo.java")
            File.WriteAllText(javaPath, java)
            let (code, so, se) = runProc tempRoot "javac" [javaPath]
            Assert.True((code = 0), $"javac failed for function-value lowering\nstdout:\n{so}\nstderr:\n{se}\nsource:\n{java}")
        finally
            try Directory.Delete(tempRoot, true) with _ -> ()

[<Fact>]
let ``Java: constrained dispatch compiles with javac`` () =
    if not (toolExists "javac") then
        ()
    else
        let src =
            "module Constrained\n\ntrait Functor F =\n  map(f A->B)(fa F[A]) F[B]\nMaybe A = Some A | None\nimpl Functor Maybe =\n  map(f A->B)(fa Maybe[A]) Maybe[B] =\n    | Some a -> Some (f a)\n    | None -> None\ntransform[F: Functor](xs F[Int])(f Int->Int) F[Int] = map f xs\nmain() Int = 0\n"
        let java = javaSrc src
        Assert.Contains("map_Maybe", java)
        Assert.Contains("transform", java)

        let tempRoot = Path.Combine(Path.GetTempPath(), "lll-java-constrained-" + Guid.NewGuid().ToString("N"))
        Directory.CreateDirectory(tempRoot) |> ignore
        try
            let javaPath = Path.Combine(tempRoot, "Constrained.java")
            File.WriteAllText(javaPath, java)
            let (code, so, se) = runProc tempRoot "javac" [javaPath]
            Assert.True((code = 0), $"javac failed\nstdout:\n{so}\nstderr:\n{se}\nsource:\n{java}")
        finally
            try Directory.Delete(tempRoot, true) with _ -> ()

// ---------- compileTarget round-trip ----------

[<Fact>]
let ``compileTarget Java produces same as compileToJava`` () =
    let src = "module M\nid(x Int) Int = x"
    let a = compileToJava src
    let b = compileTarget Java src
    Assert.Equal(a, b)

[<Fact>]
let ``compileTarget Java does not emit F# let keyword`` () =
    let src = "module M\nid(x Int) Int = x"
    match compileTarget Java src with
    | Ok java ->
        Assert.DoesNotContain("\nlet id", java)
    | Error es -> failwith $"unexpected error: {es}"

[<Fact>]
let ``compileTarget Java does not emit TypeScript syntax`` () =
    let src = "module M\nid(x Int) Int = x"
    match compileTarget Java src with
    | Ok java ->
        Assert.DoesNotContain("const ", java)
    | Error es -> failwith $"unexpected error: {es}"
