// Generated by lllc (ll-lang TypeScript backend)

// --- ll-lang stdlib (TypeScript) ---


const pi = 3.14159;

const greeting = `hello`;

const add = (a: number) => (b: number): number => (a + b);

const double = (x: number): number => (x * 2);

const square = (x: number): number => (x * x);

const clamp = (x: number) => (lo: number) => (hi: number): number => ((x < lo) ? lo : ((x > hi) ? hi : x));

const triple = (x: number) => (x * 3);

const example: number = ((y) => (y + 1))((double)(5));