// Generated by lllc (ll-lang C# backend)
// Expression-capable backend.
#nullable enable
using System;
using System.IO;
using System.Collections.Generic;


public static class LlLangProject
{
    // --- ll-lang stdlib (C#) ---
    public static long abs(long x) => Math.Abs(x);
    public static double absf(double x) => Math.Abs(x);
    public static double sqrt(double x) => Math.Sqrt(x);
    public static Func<long, long> min(long a) => b => Math.Min(a, b);
    public static Func<long, long> max(long a) => b => Math.Max(a, b);
    public static double intToFloat(long n) => (double)n;
    public static long floatToInt(double f) => (long)f;

    public static object? printfn(string s) { Console.WriteLine(s); return null; }
    public static object? print(string s) { Console.Write(s); return null; }

    public static string readFile(string path) => File.ReadAllText(path);
    public static Func<string, object?> writeFile(string path) => contents => { File.WriteAllText(path, contents); return null; };
    public static bool fileExists(string path) => File.Exists(path);
    public static object? exit(long n) { Environment.Exit(unchecked((int)n)); return null; }
    public static readonly List<string> getArgs = new(Environment.GetCommandLineArgs());

    public static long strLen(string s) => s.Length;
    public static Func<object, string> strConcat(string a) => b => a + (b?.ToString() ?? "");
    public static string strTrim(string s) => s.Trim();
    public static Func<object, bool> strContains(string needle) => hay => (hay?.ToString() ?? "").Contains(needle);
    public static Func<string, List<string>> strSplit(string sep) =>
        s => new List<string>(s.Split(sep, StringSplitOptions.None));
    public static Func<long, Func<long, string>> strSlice(string s) =>
        start => len => {
            var i = (int)start;
            var n = (int)len;
            if (i < 0 || n <= 0 || i >= s.Length) return "";
            var max = s.Length - i;
            if (n > max) n = max;
            return s.Substring(i, n);
        };
    public static Func<string, long> strIndexOf(string needle) =>
        hay => hay.IndexOf(needle, StringComparison.Ordinal);
    public static string strReverse(string s) { var a = s.ToCharArray(); Array.Reverse(a); return new string(a); }
    public static string strFromChars(IEnumerable<char> cs) => new string(new List<char>(cs).ToArray());
    public static List<char> strChars(string s) => new(s.ToCharArray());
    public static string intToStr(long n) => n.ToString();
    public static string floatToStr(double f) => f.ToString(System.Globalization.CultureInfo.InvariantCulture);
    public static object? strToInt(string s) => long.TryParse(s, out var n) ? n : null;
    public static object? strToFloat(string s) => double.TryParse(s, out var n) ? n : null;

    public static long charToInt(char c) => c;
    public static char intToChar(long n) => (char)n;
    public static bool charIsDigit(char c) => char.IsDigit(c);
    public static bool charIsAlpha(char c) => char.IsLetter(c);
    public static bool charIsSpace(char c) => char.IsWhiteSpace(c);

    public static long listLen<T>(List<T> xs) => xs.Count;
    public static Func<List<A>, List<B>> listMap<A, B>(Func<A, B> f) =>
        xs => { var r = new List<B>(xs.Count); foreach (var x in xs) r.Add(f(x)); return r; };
    public static Func<List<A>, List<A>> listFilter<A>(Func<A, bool> p) =>
        xs => { var r = new List<A>(); foreach (var x in xs) if (p(x)) r.Add(x); return r; };
    public static Func<B, Func<List<A>, B>> listFold<A, B>(Func<B, Func<A, B>> f) =>
        z => xs => { var acc = z; foreach (var x in xs) acc = f(acc)(x); return acc; };
    public static T? listHead<T>(List<T> xs) =>
        xs.Count > 0 ? xs[0] : default;
    public static List<T>? listTail<T>(List<T> xs) =>
        xs.Count > 0 ? new List<T>(xs.GetRange(1, xs.Count - 1)) : null;
    public static List<T> listReverse<T>(List<T> xs) {
        var r = new List<T>(xs);
        r.Reverse();
        return r;
    }
    public static Func<List<T>, List<T>> listAppend<T>(List<T> xs) =>
        ys => { var r = new List<T>(xs.Count + ys.Count); r.AddRange(xs); r.AddRange(ys); return r; };
    public static bool listIsEmpty<T>(List<T> xs) => xs.Count == 0;
    public static Func<T, bool> listContains<T>(List<T> xs) => x => xs.Contains(x);
    public static Func<long, List<long>> listRange(long lo) => hi => {
        var r = new List<long>();
        for (long i = lo; i < hi; i++) r.Add(i);
        return r;
    };
    public static List<T> listConcat<T>(List<List<T>> xss) {
        var r = new List<T>();
        foreach (var xs in xss)
            r.AddRange(xs);
        return r;
    }
    public static Func<long, T?> listAt<T>(List<T> xs) => i =>
        i >= 0 && i < xs.Count ? xs[(int)i] : default;

    public static Func<object, object?> maybeMap(Func<object, object> f) =>
        m => m is null ? null : f(m);
    public static Func<Func<object, object?>, object?> maybeBind(object? m) =>
        f => m is null ? null : f(m);
    public static Func<object?, object> maybeWithDefault(object d) =>
        m => m ?? d;
    public static Func<object?, object> maybeDefault(object d) =>
        maybeWithDefault(d);
    public static bool maybeIsNone(object? m) => m is null;
    // --- end prelude ---


    public interface Maybe<A> { }
    public sealed record Some<A>(A _0) : Maybe<A>;
    public sealed record None<A>() : Maybe<A>;

    public static bool isNone<A>(Maybe<A> m) => false;

    public static bool isSome<A>(Maybe<A> m) => false;

    public static Func<bool, long> check(string label) => ok => 0L;

    public static Maybe<long> doubleInMaybe(long x) => new Some<long>((x * 2L));

    public static long __ll_main_Std_Maybe() => 0L;

    public interface Token { }
    public sealed record KwLet() : Token;
    public sealed record KwTag() : Token;
    public sealed record KwUnit() : Token;
    public sealed record KwTrait() : Token;
    public sealed record KwImpl() : Token;
    public sealed record KwImport() : Token;
    public sealed record KwExport() : Token;
    public sealed record KwModule() : Token;
    public sealed record KwIf() : Token;
    public sealed record KwElse() : Token;
    public sealed record KwTrue() : Token;
    public sealed record KwFalse() : Token;
    public sealed record KwMatch() : Token;
    public sealed record Ident(string _0) : Token;
    public sealed record TypeId(string _0) : Token;
    public sealed record IntLit(long _0) : Token;
    public sealed record FloatLit(string _0) : Token;
    public sealed record StrLit(string _0) : Token;
    public sealed record CharLit(char _0) : Token;
    public sealed record Arrow() : Token;
    public sealed record Backslash() : Token;
    public sealed record Dot() : Token;
    public sealed record Comma() : Token;
    public sealed record Colon() : Token;
    public sealed record ColonColon() : Token;
    public sealed record Eq() : Token;
    public sealed record Bar() : Token;
    public sealed record LBrack() : Token;
    public sealed record RBrack() : Token;
    public sealed record LParen() : Token;
    public sealed record RParen() : Token;
    public sealed record Plus() : Token;
    public sealed record Minus() : Token;
    public sealed record Star() : Token;
    public sealed record Slash() : Token;
    public sealed record Caret() : Token;
    public sealed record Lt() : Token;
    public sealed record Gt() : Token;
    public sealed record Le() : Token;
    public sealed record Ge() : Token;
    public sealed record EqEq() : Token;
    public sealed record Neq() : Token;
    public sealed record Underscore() : Token;
    public sealed record Newline() : Token;
    public sealed record Indent() : Token;
    public sealed record Dedent() : Token;
    public sealed record Eof() : Token;
    public sealed record TError(char _0) : Token;

    public static bool isUpperChar(char c) => ((Func<bool>)(() => { var n = charToInt(c); return ((n < 65L) ? false : ((n > 90L) ? false : true)); }))();

    public static bool isLowerChar(char c) => ((Func<bool>)(() => { var n = charToInt(c); return ((n < 97L) ? false : ((n > 122L) ? false : true)); }))();

    public static bool isIdStart(char c) => (isUpperChar(c) ? true : isLowerChar(c));

    public static bool isIdCont(char c) => (isIdStart(c) ? true : (charIsDigit(c) ? true : (c == '_')));

    public static List<char> takeIdCont(List<char> cs) => new List<char>();

    public static List<char> dropIdCont(List<char> cs) => new List<char>();

    public static List<char> takeDigit(List<char> cs) => new List<char>();

    public static List<char> dropDigit(List<char> cs) => new List<char>();

    public static Token classifyIdent(string s) => default!;

    public static long parseIntStr(string s) => 0L;

    public static List<Token> lexId(List<char> cs) => ((Func<List<Token>>)(() => { var idChars = takeIdCont(cs); return ((Func<List<Token>>)(() => { var leftover = dropIdCont(cs); return ((Func<List<Token>>)(() => { var tok = classifyIdent(strFromChars(idChars)); return (listAppend<Token>(new List<Token> { tok }))(lexChars(leftover)); }))(); }))(); }))();

    public static List<Token> lexNum(List<char> cs) => new List<Token>();

    public static Tuple<List<char>, List<char>> takeStrBody(List<char> cs) => default!;

    public static Tuple<List<char>, List<char>> takeStrBodyEsc(List<char> cs) => default!;

    public static char decodeEscape(char c) => '\0';

    public static List<Token> lexStr(List<char> cs) => new List<Token>();

    public static List<Token> lexCharLit(List<char> cs) => new List<Token>();

    public static List<Token> skipLineComment(List<char> cs) => new List<Token>();

    public static List<Token> lexEqOrEqEq(List<char> cs) => new List<Token>();

    public static List<Token> lexNeq(List<char> cs) => new List<Token>();

    public static List<Token> lexLtOrLe(List<char> cs) => new List<Token>();

    public static List<Token> lexGtOrGe(List<char> cs) => new List<Token>();

    public static List<Token> lexMinusOrArrow(List<char> cs) => new List<Token>();

    public static List<Token> lexColonOrCons(List<char> cs) => new List<Token>();

    public static List<Token> lexUnderOrIdent(List<char> cs) => new List<Token>();

    public static List<Token> lexChars(List<char> cs) => new List<Token>();

    public static List<Token> tokenize(string src) => lexChars(strChars(src));

    public static string showToken(Token t) => "";

    public static string showTokens(List<Token> ts) => ((listFold<Token,string>(acc => t => ((Func<string>)(() => { var s = showToken(t); return ((strLen(acc) == 0L) ? ((s)?.ToString() ?? "") : (((strConcat(strConcat(acc)(" ")))(s))?.ToString() ?? "")); }))()))(""))(ts);

    public static List<Token> stripNewlines(List<Token> ts) => new List<Token>();

    public static Func<string, Func<string, object>> checkTokens(string label) => src => expected => ((Func<object>)(() => { var got = showTokens(stripNewlines(tokenize(src))); return ((got == expected) ? printfn((strConcat("OK "))(label)) : ((Func<object>)(() => { var p1 = (strConcat("FAIL "))(label); return ((Func<object>)(() => { var p2 = strConcat(p1)("\n  expected: "); return ((Func<object>)(() => { var p3 = strConcat(p2)(expected); return ((Func<object>)(() => { var p4 = strConcat(p3)("\n  got:      "); return ((Func<object>)(() => { var p5 = strConcat(p4)(got); return printfn(p5); }))(); }))(); }))(); }))(); }))()); }))();

    public static long __ll_main_Std_Lexer() => 0L;

    public interface Pattern { }
    public sealed record PVar(string _0) : Pattern;
    public sealed record PWild() : Pattern;
    public sealed record PCon(string _0, List<Pattern> _1) : Pattern;
    public sealed record PLitInt(long _0) : Pattern;
    public sealed record PLitStr(string _0) : Pattern;
    public sealed record PCons(Pattern _0, Pattern _1) : Pattern;
    public sealed record PNil() : Pattern;

    public interface Expr { }
    public sealed record EInt(long _0) : Expr;
    public sealed record EStr(string _0) : Expr;
    public sealed record EBool(bool _0) : Expr;
    public sealed record EChar(char _0) : Expr;
    public sealed record EFloat(string _0) : Expr;
    public sealed record EVar(string _0) : Expr;
    public sealed record ECon(string _0) : Expr;
    public sealed record EApp(Expr _0, Expr _1) : Expr;
    public sealed record EIf(Expr _0, Expr _1, Expr _2) : Expr;
    public sealed record EMatch(Expr _0, List<Pattern> _1, List<Expr> _2) : Expr;
    public sealed record ELam(string _0, Expr _1) : Expr;
    public sealed record ELet(string _0, Expr _1, Expr _2) : Expr;
    public sealed record EList(List<Expr> _0) : Expr;
    public sealed record EBinOp(string _0, Expr _1, Expr _2) : Expr;
    public sealed record ETuple(Expr _0, Expr _1) : Expr;
    public sealed record ENil() : Expr;
    public sealed record ECons(Expr _0, Expr _1) : Expr;

    public interface TypeExpr { }
    public sealed record TyName(string _0) : TypeExpr;
    public sealed record TyApp(TypeExpr _0, TypeExpr _1) : TypeExpr;
    public sealed record TyFn(TypeExpr _0, TypeExpr _1) : TypeExpr;

    public interface Param { }
    public sealed record MkParam(string _0, TypeExpr _1) : Param;

    public interface Constructor { }
    public sealed record MkCon(string _0, List<TypeExpr> _1) : Constructor;

    public interface Decl { }
    public sealed record DFn(string _0, List<Param> _1, Maybe<TypeExpr> _2, Expr _3) : Decl;
    public sealed record DType(string _0, List<string> _1, List<Constructor> _2) : Decl;
    public sealed record DImport(List<string> _0) : Decl;
    public sealed record DExport(Decl _0) : Decl;
    public sealed record DLet(string _0, Expr _1) : Decl;

    public interface Module { }
    public sealed record MkModule(List<string> _0, List<Decl> _1) : Module;

    public static List<Token> skipNewlines(List<Token> toks) => new List<Token>();

    public static bool isAtomStart(Token t) => false;

    public static List<Token> skipBrackTypeArgs(List<Token> toks) => new List<Token>();

    public static List<Token> skipBrackTypeBody(List<Token> toks) => new List<Token>();

    public static Tuple<TypeExpr, List<Token>> parseTypeExpr(List<Token> toks) => default!;

    public static Tuple<Maybe<TypeExpr>, List<Token>> parseReturnType(List<Token> toks) => default!;

    public static Tuple<List<Param>, List<Token>> parseParamGroups(List<Token> toks) => default!;

    public static Tuple<List<string>, List<Token>> parseTypeParams(List<Token> toks) => default!;

    public static Tuple<List<TypeExpr>, List<Token>> parseConArgs(List<Token> toks) => default!;

    public static Tuple<Constructor, List<Token>> parseCon(List<Token> toks) => default!;

    public static Func<List<Token>, Tuple<List<Constructor>, List<Token>>> parseConsTail(List<Constructor> acc) => toks => default!;

    public static Tuple<List<Constructor>, List<Token>> parseConList(List<Token> toks) => default!;

    public static Tuple<Decl, List<Token>> parseTypeDecl(List<Token> toks) => default!;

    public static Tuple<Pattern, List<Token>> parsePrimaryPat(List<Token> toks) => default!;

    public static Tuple<List<object>, List<Token>> parsePatArgs(List<Token> toks) => default!;

    public static Tuple<List<Pattern>, List<Token>> parsePatArgsCons(List<Token> toks) => default!;

    public static Tuple<Pattern, List<Token>> parsePat(List<Token> toks) => default!;

    public static object parseArmBody(List<Token> toks) => default!;

    public static List<Token> skipArrow(List<Token> toks) => new List<Token>();

    public static Tuple<Tuple<Pattern, Expr>, List<Token>> parseArm(List<Token> toks) => default!;

    public static Tuple<Tuple<List<Pattern>, List<Expr>>, List<Token>> parseArms(List<Token> toks) => default!;

    public static Tuple<Expr, List<Token>> parseMatch(List<Token> toks) => default!;

    public static Tuple<Expr, List<Token>> parseIf(List<Token> toks) => default!;

    public static List<Token> skipKwIn(List<Token> toks) => new List<Token>();

    public static Tuple<Expr, List<Token>> parseLetIn(List<Token> toks) => default!;

    public static Func<List<Token>, Tuple<List<string>, List<Token>>> parseLamParams(List<string> acc) => toks => default!;

    public static Func<Expr, Expr> wrapLamParams(List<string> parms) => body => default!;

    public static Tuple<Expr, List<Token>> parseLam(List<Token> toks) => default!;

    public static Tuple<Expr, List<Token>> parseExpr(List<Token> toks) => default!;

    public static object parseCompare(List<Token> toks) => default!;

    public static Func<List<Token>, Tuple<Expr, List<Token>>> parseCompareTail(Expr lhs) => toks => default!;

    public static Tuple<Expr, List<Token>> parseCons(List<Token> toks) => default!;

    public static object parseAddSub(List<Token> toks) => default!;

    public static Func<List<Token>, Tuple<Expr, List<Token>>> parseAddSubTail(Expr lhs) => toks => default!;

    public static object parseMulDiv(List<Token> toks) => default!;

    public static Func<List<Token>, Tuple<Expr, List<Token>>> parseMulDivTail(Expr lhs) => toks => default!;

    public static object parseApp(List<Token> toks) => default!;

    public static Func<List<Token>, Tuple<Expr, List<Token>>> parseAppTail(Expr lhs) => toks => default!;

    public static Tuple<Expr, List<Token>> parseListLit(List<Token> toks) => default!;

    public static object parseListElem(List<Token> toks) => default!;

    public static Func<List<Token>, Tuple<Expr, List<Token>>> parseAtomParenTail(Expr e) => toks => default!;

    public static Tuple<Expr, List<Token>> parseAtom(List<Token> toks) => default!;

    public static Expr lastParamVar(List<Param> prms) => default!;

    public static Func<List<Token>, Tuple<Expr, List<Token>>> parseFnBody(List<Param> prms) => toks => default!;

    public static Tuple<Decl, List<Token>> parseFnDecl(List<Token> toks) => default!;

    public static Tuple<Decl, List<Token>> parseLetDecl(List<Token> toks) => default!;

    public static Func<List<Token>, Tuple<List<string>, List<Token>>> parseImportPath(List<string> acc) => toks => default!;

    public static Tuple<Decl, List<Token>> parseImportDecl(List<Token> toks) => default!;

    public static Tuple<Decl, List<Token>> parseOneDecl(List<Token> toks) => default!;

    public static List<Decl> parseDecls(List<Token> toks) => new List<Decl>();

    public static Func<List<Token>, Tuple<List<string>, List<Token>>> parseModulePath(List<string> acc) => toks => default!;

    public static Tuple<List<string>, List<Token>> parseModuleHeader(List<Token> toks) => default!;

    public static Module parseModule(List<Token> toks) => default!;

    public static string boolToStr(bool b) => (b ? (("true")?.ToString() ?? "") : (("false")?.ToString() ?? ""));

    public static string showExpr(Expr e) => "";

    public static string showPattern(Pattern p) => "";

    public static string showMaybeTy(Maybe<TypeExpr> m) => "";

    public static string joinDot(List<string> segs) => ((listFold<string,string>(acc => s => ((strLen(acc) == 0L) ? ((s)?.ToString() ?? "") : ((strConcat(strConcat(acc)("."))(s))?.ToString() ?? ""))))(""))(segs);

    public static string showDecl(Decl d) => "";

    public static Func<List<Token>, Func<string, object>> parserCheckExpr(string label) => toks => expected => null;

    public static Func<List<Token>, Func<string, object>> parserCheckDecl(string label) => toks => expected => null;

    public static Func<List<Token>, Func<long, object>> parserCheckModule(string label) => toks => expectedDeclCount => null;

    public static long __ll_main_Std_Parser() => 0L;

    public static Func<List<string>, string> joinWith(string sep) => items => "";

    public static string encodeStrEscape(char c) => "";

    public static string escapeStr(string s) => ((listFold<char,string>(acc => c => strConcat(acc)(encodeStrEscape(c))))(""))(strChars(s));

    public static string emitCharLit(char c) => "";

    public static string emitType(TypeExpr t) => "";

    public static string emitTypeAtom(TypeExpr t) => "";

    public static string emitParam(Param p) => "";

    public static string emitParams(List<Param> ps) => joinWith("")(listMap<Param,string>(emitParam)(ps));

    public static string emitCtor(Constructor c) => "";

    public static bool isAtomicExpr(Expr e) => false;

    public static string emitExprAtom(Expr e) => (isAtomicExpr(e) ? ((emitExpr(e))?.ToString() ?? "") : ((strConcat("(")(strConcat(emitExpr(e))(")")))?.ToString() ?? ""));

    public static string emitPattern(Pattern p) => "";

    public static string emitPatternAtom(Pattern p) => "";

    public static Expr gatherAppHead(Expr e) => default!;

    public static List<object> gatherAppArgs(Expr e) => new List<object>();

    public static List<object> gatherLamNames(Expr e) => new List<object>();

    public static Expr gatherLamBody(Expr e) => default!;

    public static Func<List<Expr>, string> emitArms(List<Pattern> pats) => bodies => "";

    public static string emitExpr(Expr e) => "";

    public static string emitDecl(Decl d) => "";

    public static string emitDecls(List<Decl> ds) => joinWith("\n\n")(listMap<Decl,string>(emitDecl)(ds));

    public static string renderModule(Module m) => "";

    public interface ElabError { }
    public sealed record MkError(string _0) : ElabError;

    public static object errMsg(ElabError e) => default!;

    public interface Env { }
    public sealed record MkEnv(List<string> _0) : Env;

    public static Env emptyEnv() => new MkEnv(new List<string> {  });

    public static Func<Env, Env> envAdd(string name) => env => default!;

    public static Func<Env, Env> envAddAll(List<string> names) => env => ((listFold<string,Env>(acc => n => envAdd(n)(acc)))(env))(names);

    public static Func<bool, Func<string, bool>> strOrEq(string target) => acc => x => (acc ? true : (x == target));

    public static Func<Env, bool> envHas(string name) => env => false;

    public static List<object> patBinders(Pattern p) => new List<object>();

    public static List<object> patBindersList(List<Pattern> ps) => new List<object>();

    public static object paramName(Param p) => default!;

    public static List<object> paramNames(List<Param> ps) => (listMap<Param,object>(p => paramName(p)))(ps);

    public static object conName(Constructor c) => default!;

    public static List<object> conNames(List<Constructor> cs) => (listMap<Constructor,object>(c => conName(c)))(cs);

    public static Func<List<string>, bool> listContains(string name) => xs => ((listFold<string,bool>(acc => x => strOrEq(name)(acc)(x)))(false))(xs);

    public static Func<List<string>, List<string>> findDuplicatesAcc(List<string> xs) => seen => new List<string>();

    public static List<string> findDuplicates(List<string> xs) => findDuplicatesAcc(xs)(new List<string> {  });

    public static Maybe<object> declName(Decl d) => default;

    public static Func<Decl, List<string>> addDeclName(List<string> acc) => d => new List<string>();

    public static List<string> collectDeclNames(List<Decl> decls) => ((listFold<Decl,List<string>>(acc => d => addDeclName(acc)(d)))(new List<string> {  }))(decls);

    public static Func<Env, Env> collectDecl(Decl d) => env => default!;

    public static Func<Env, Env> collectDecls(List<Decl> decls) => env => ((listFold<Decl,Env>(acc => d => collectDecl(d)(acc)))(env))(decls);

    public static Func<Expr, List<ElabError>> checkExpr(Env env) => e => new List<ElabError>();

    public static Func<Pattern, Func<List<Pattern>, Func<List<Expr>, List<ElabError>>>> checkArmsCons(Env env) => p => restPats => bodies => new List<ElabError>();

    public static Func<List<Pattern>, Func<List<Expr>, List<ElabError>>> checkArms(Env env) => pats => bodies => new List<ElabError>();

    public static Func<Decl, List<ElabError>> checkDecl(Env env) => d => new List<ElabError>();

    public static Func<List<Decl>, List<ElabError>> checkDecls(Env env) => decls => ((listFold<Decl,List<ElabError>>(acc => d => listAppend<ElabError>(acc)(checkDecl(env)(d))))(new List<ElabError> {  }))(decls);

    public static ElabError makeDupError(string name) => new MkError((strConcat("Duplicate declaration: "))(name));

    public static List<ElabError> checkDuplicates(List<Decl> decls) => ((Func<List<ElabError>>)(() => { var names = collectDeclNames(decls); return ((Func<List<ElabError>>)(() => { var dups = findDuplicates(names); return (listMap<string,ElabError>(name => makeDupError(name)))(dups); }))(); }))();

    public static List<string> builtinNames() => new List<string>();

    public static List<ElabError> elaborate(Module m) => new List<ElabError>();

    public static Func<List<ElabError>, object> assertNoErrors(string label) => errs => (listIsEmpty<ElabError>(errs) ? printfn((strConcat("OK "))(label)) : printfn((strConcat("FAIL "))(strConcat(label)(" — unexpected errors"))));

    public static Func<ElabError, bool> errContains(string needle) => e => strContains(needle)(errMsg(e));

    public static Func<bool, Func<ElabError, bool>> errOrContains(string needle) => acc => e => (acc ? true : errContains(needle)(e));

    public static Func<List<ElabError>, bool> hasErrorWith(string needle) => errs => ((listFold<ElabError,bool>(acc => e => errOrContains(needle)(acc)(e)))(false))(errs);

    public static Func<string, Func<List<ElabError>, object>> assertHasError(string label) => needle => errs => (hasErrorWith(needle)(errs) ? printfn((strConcat("OK "))(label)) : printfn((strConcat("FAIL "))(strConcat(label)((strConcat(" — expected error: "))(needle)))));

    public static long __ll_main_Std_Elaborator() => 0L;

    public static bool isFsKeyword(string s) => false;

    public static string safeIdent(string s) => (isFsKeyword(s) ? ((strConcat("__ll_")(s))?.ToString() ?? "") : ((s)?.ToString() ?? ""));

    public static string mapOp(string op) => ((op == "==") ? (("=")?.ToString() ?? "") : ((((op == "!=") ? (("<>")?.ToString() ?? "") : ((op)?.ToString() ?? "")))?.ToString() ?? ""));

    public static bool isTypeParam(string s) => false;

    public static TypeExpr collectTyAppHead(TypeExpr t) => default!;

    public static List<object> collectTyAppArgs(TypeExpr t) => new List<object>();

    public static Func<List<Pattern>, string> emitConPattern(string c) => args => "";

    public static Pattern patListHead(List<Pattern> xs) => default!;

    public static bool isUpperStart(string s) => false;

    public static Func<Expr, string> emitApp(Expr f) => a => "";

    public static Expr exprListHead(List<Expr> xs) => default!;

    public static Func<List<Expr>, string> emitConApp(string c) => args => "";

    public static string emitTypeParam(string s) => strConcat("'")(s);

    public static string emitTypeParams(List<string> tvars) => "";

    public static string emitCtorArgs(List<TypeExpr> args) => (joinWith(" * "))(listMap<TypeExpr,string>(emitType)(args));

    public static string emitCtors(List<Constructor> cs) => joinWith("\n")(listMap<Constructor,string>(emitCtor)(cs));

    public static string emitParamName(Param p) => "";

    public static string emitParamStr(List<Param> ps) => "";

    public static string emitPrelude() => "// --- ll-lang stdlib prelude (auto-generated) ---\nlet listLen (xs: 'a list) : int64 = int64 (List.length xs)\nlet listMap f xs = List.map f xs\nlet listFilter p xs = List.filter p xs\nlet listFold f z xs = List.fold f z xs\nlet listReverse xs = List.rev xs\nlet listAppend xs ys = List.append xs ys\nlet listConcat xss = List.concat xss\nlet listIsEmpty xs = List.isEmpty xs\nlet strLen (s: string) : int64 = int64 s.Length\nlet strConcat (a: string) (b: string) = a + b\nlet strChars (s: string) = s |> Seq.toList\nlet strFromChars (cs: char list) = System.String(cs |> List.toArray)\nlet intToStr (n: int64) = string n\nlet charToInt (c: char) = int64 (int c)\nlet printfn (s: string) = System.Console.WriteLine(s)\nlet print (s: string) = System.Console.Write(s)\nlet listHead xs = match xs with [] -> None | x :: _ -> Some x\nlet listTail xs = match xs with [] -> None | _ :: t -> Some t\n// --- end prelude ---";

    public static string emitModulePath(List<string> parts) => joinWith(".")(parts);

    public static string emitModule(Module m) => "";

    public static Func<string, Func<string, object>> codegenCheck(string label) => got => expected => ((got == expected) ? printfn((strConcat("OK "))(label)) : printfn((strConcat("FAIL "))(strConcat(label)((strConcat("\n  got:      "))(strConcat(got)((strConcat("\n  expected: "))(expected)))))));

    public static Func<string, Func<string, object>> checkContains(string label) => got => needle => (strContains(needle)(got) ? printfn((strConcat("OK "))(label)) : printfn((strConcat("FAIL "))(strConcat(label)((strConcat("\n  missing: "))(strConcat(needle)((strConcat("\n  in: "))(got)))))));

    public static long __ll_main_Std_Codegen() => 0L;

    public static string showErrors(List<ElabError> errs) => ((listFold<ElabError,string>(acc => e => ((Func<string>)(() => { var msg = errMsg(e); return ((strLen(acc) == 0L) ? ((msg)?.ToString() ?? "") : ((strConcat(acc)(strConcat("\n")(msg)))?.ToString() ?? "")); }))()))(""))(errs);

    public static string encodeJsonEscape(char c) => "";

    public static string escapeJson(string s) => ((listFold<char,string>(acc => c => strConcat(acc)(encodeJsonEscape(c))))(""))(strChars(s));

    public static string jsonStr(string s) => strConcat("\"")(strConcat(escapeJson(s))("\""));

    public static string firstError(List<ElabError> errs) => "";

    public static long secondaryErrorCount(List<ElabError> errs) => 0L;

    public static string declPrimaryName(Decl d) => "";

    public static string declKindTag(Decl d) => "";

    public static Func<List<Decl>, string> findSymbolKind(string name) => decls => "";

    public static bool hasLexErrors(List<Token> tokens) => false;

    public static string firstLexError(List<Token> tokens) => "";

    public static long countAllTokens(List<Token> tokens) => 0L;

    public static long countCodeTokens(List<Token> tokens) => 0L;

    public static string checkCompact(string src) => "";

    public static string nextBlocker(string src) => "";

    public static Func<string, string> lookupSymbol(string src) => name => "";

    public static string compileCompact(string src) => "";

    public static string renderCompact(string src) => ((Func<string>)(() => { var tokens = tokenize(src); return ((Func<string>)(() => { var ast = parseModule(tokens); return renderModule(ast); }))(); }))();

    public static string tokenEstimate(string src) => ((Func<string>)(() => { var tokens = tokenize(src); return ((Func<string>)(() => { var p1 = "{\"ok\":true,\"source_bytes\":"; return ((Func<string>)(() => { var p2 = strConcat(p1)(intToStr(strLen(src))); return ((Func<string>)(() => { var p3 = strConcat(p2)(",\"lexer_tokens\":"); return ((Func<string>)(() => { var p4 = strConcat(p3)(intToStr(countAllTokens(tokens))); return ((Func<string>)(() => { var p5 = strConcat(p4)(",\"non_layout_tokens\":"); return strConcat(p5)(strConcat(intToStr(countCodeTokens(tokens)))("}")); }))(); }))(); }))(); }))(); }))(); }))();

    public static string compile(string src) => "";

    public static Func<string, Func<string, object>> compilerCheckContains(string label) => got => needle => (strContains(needle)(got) ? printfn((strConcat("OK "))(label)) : printfn((strConcat("FAIL "))(strConcat(label)((strConcat("\n  missing:  "))(strConcat(needle)((strConcat("\n  in output:\n"))(got)))))));

    public static Func<string, Func<string, object>> checkHasError(string label) => got => needle => (strContains(needle)(got) ? printfn((strConcat("OK "))(label)) : printfn((strConcat("FAIL "))(strConcat(label)((strConcat("\n  expected error containing: "))(strConcat(needle)((strConcat("\n  got: "))(got)))))));

    public static int Main(string[] args) => 0;
}
