// @ts-nocheck
// Generated by lllc (ll-lang TypeScript backend)

type Maybe<A> = { _tag: `Some`; _0: unknown } | { _tag: `None` };
const Some = <A>(_0: unknown): Maybe<A> => ({ _tag: `Some` as const, _0 });
const None: Maybe<unknown> = { _tag: `None` as const };

// --- ll-lang stdlib (TypeScript) ---

const charIsDigit = (c: string): boolean => /\d/.test(c);

const charIsSpace = (c: string): boolean => /\s/.test(c);

const charToInt = (c: string): number => c.charCodeAt(0);

const intToStr = (n: number): string => String(n);

const listAppend = <T>(xs: T[]) => (ys: T[]): T[] => [...xs, ...ys];

const listConcat = <T>(xss: T[][]): T[] => xss.flat();

const listFilter = <A>(p: (x: A) => boolean) => (xs: A[]): A[] => xs.filter(p);

const listFold = <A, B>(f: (acc: B) => (x: A) => B) => (z: B) => (xs: A[]): B => xs.reduce((a, x) => f(a)(x), z);

const listHead = <T>(xs: T[]) => xs.length > 0 ? ({ _tag: `Some` as const, _0: xs[0] }) : ({ _tag: `None` as const });

const listLen = <T>(xs: T[]): number => xs.length;

const listMap = <A, B>(f: (x: A) => B) => (xs: A[]): B[] => xs.map(f);

const listReverse = <T>(xs: T[]): T[] => [...xs].reverse();

const maybeWithDefault = <A>(d: A) => (m: A | null): A => m !== null ? m : d;

const printfn = (s: string): void => { console.log(s) };

const strChars = (s: string): string[] => Array.from(s);

const strConcat = (a: string) => (b: string): string => a + b;

const strFromChars = (cs: string[]): string => cs.join('');

const strLen = (s: string): number => s.length;

const strSlice = (s: string) => (start: number) => (len: number): string => s.slice(start, start + len);

const strToInt = (s: string) => { const n = parseInt(s, 10); return isNaN(n) ? ({ _tag: `None` as const }) : ({ _tag: `Some` as const, _0: n }); };

const isNone = (m: unknown | null) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Some`) {  return false; }
  if (_ll_s?._tag === `None`) { return true; }
  throw new Error(`Non-exhaustive match`);
})();

const isSome = (m: unknown | null) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Some`) {  return true; }
  if (_ll_s?._tag === `None`) { return false; }
  throw new Error(`Non-exhaustive match`);
})();

const check = (label: string) => (ok: boolean) => (ok ? ((_) => 0)((printfn)(((strConcat)(`OK `))(label))) : ((_) => 1)((printfn)(((strConcat)(`FAIL `))(label))));

const doubleInMaybe = (x: number) => Some((x * 2));

const maybeCheck = (label: string) => (got: string) => (expected: string) => ((got === expected) ? (printfn)(((strConcat)(`OK `))(label)) : (printfn)(((strConcat)(`FAIL `))(((strConcat)(label))(((strConcat)(` expected=`))(((strConcat)(expected))(((strConcat)(` got=`))(got)))))));

const boolStr = (b: boolean) => (b ? `true` : `false`);

const maybeIntStr = (m: number | null) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Some`) { const v = (_ll_s as Record<string, unknown>)[`_0`]; return (intToStr)(v); }
  if (_ll_s?._tag === `None`) { return `none`; }
  throw new Error(`Non-exhaustive match`);
})();

const __ll_main_Std_Maybe = () => {};

type Color = { _tag: `Red` } | { _tag: `Black` };
const Red: Color = { _tag: `Red` as const };
const Black: Color = { _tag: `Black` as const };

type RBMap<K, V> = { _tag: `Leaf` } | { _tag: `Node`; _0: Color; _1: RBMap<unknown, unknown>; _2: unknown; _3: unknown; _4: RBMap<unknown, unknown> };
const Leaf: RBMap<unknown> = { _tag: `Leaf` as const };
const Node = <K, V>(_0: Color, _1: RBMap<unknown, unknown>, _2: unknown, _3: unknown, _4: RBMap<unknown, unknown>): RBMap<K, V> => ({ _tag: `Node` as const, _0, _1, _2, _3, _4 });

const mapEmpty = (() => Leaf)();

const mapSize = (m: RBMap<unknown, unknown>) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Leaf`) { return 0; }
  if (_ll_s?._tag === `Node`) { const left = (_ll_s as Record<string, unknown>)[`_1`]; const right = (_ll_s as Record<string, unknown>)[`_4`]; return ((1 + (mapSize)(left)) + (mapSize)(right)); }
  throw new Error(`Non-exhaustive match`);
})();

const balanceLeft = (left: RBMap<unknown, unknown>) => (k: unknown) => (v: unknown) => (right: RBMap<unknown, unknown>) => (() => {
  const _ll_s = left;
  if (_ll_s?._tag === `Node`) { const ll = (_ll_s as Record<string, unknown>)[`_1`]; const lk = (_ll_s as Record<string, unknown>)[`_2`]; const lv = (_ll_s as Record<string, unknown>)[`_3`]; const lr = (_ll_s as Record<string, unknown>)[`_4`]; return (() => {
  const _ll_s = ll;
  if (_ll_s?._tag === `Node`) { const a = (_ll_s as Record<string, unknown>)[`_1`]; const xk = (_ll_s as Record<string, unknown>)[`_2`]; const xv = (_ll_s as Record<string, unknown>)[`_3`]; const b = (_ll_s as Record<string, unknown>)[`_4`]; return Node(Red, Node(Black, a, xk, xv, b), lk, lv, Node(Black, lr, k, v, right)); }
  return (() => {
  const _ll_s = lr;
  if (_ll_s?._tag === `Node`) { const b = (_ll_s as Record<string, unknown>)[`_1`]; const yk = (_ll_s as Record<string, unknown>)[`_2`]; const yv = (_ll_s as Record<string, unknown>)[`_3`]; const c = (_ll_s as Record<string, unknown>)[`_4`]; return Node(Red, Node(Black, ll, lk, lv, b), yk, yv, Node(Black, c, k, v, right)); }
  return Node(Black, left, k, v, right);
  throw new Error(`Non-exhaustive match`);
})();
  throw new Error(`Non-exhaustive match`);
})(); }
  return Node(Black, left, k, v, right);
  throw new Error(`Non-exhaustive match`);
})();

const balanceRight = (left: RBMap<unknown, unknown>) => (k: unknown) => (v: unknown) => (right: RBMap<unknown, unknown>) => (() => {
  const _ll_s = right;
  if (_ll_s?._tag === `Node`) { const rl = (_ll_s as Record<string, unknown>)[`_1`]; const rk = (_ll_s as Record<string, unknown>)[`_2`]; const rv = (_ll_s as Record<string, unknown>)[`_3`]; const rr = (_ll_s as Record<string, unknown>)[`_4`]; return (() => {
  const _ll_s = rl;
  if (_ll_s?._tag === `Node`) { const b = (_ll_s as Record<string, unknown>)[`_1`]; const yk = (_ll_s as Record<string, unknown>)[`_2`]; const yv = (_ll_s as Record<string, unknown>)[`_3`]; const c = (_ll_s as Record<string, unknown>)[`_4`]; return Node(Red, Node(Black, left, k, v, b), yk, yv, Node(Black, c, rk, rv, rr)); }
  return (() => {
  const _ll_s = rr;
  if (_ll_s?._tag === `Node`) { const c = (_ll_s as Record<string, unknown>)[`_1`]; const zk = (_ll_s as Record<string, unknown>)[`_2`]; const zv = (_ll_s as Record<string, unknown>)[`_3`]; const d = (_ll_s as Record<string, unknown>)[`_4`]; return Node(Red, Node(Black, left, k, v, rl), rk, rv, Node(Black, c, zk, zv, d)); }
  return Node(Black, left, k, v, right);
  throw new Error(`Non-exhaustive match`);
})();
  throw new Error(`Non-exhaustive match`);
})(); }
  return Node(Black, left, k, v, right);
  throw new Error(`Non-exhaustive match`);
})();

const balance = (c: Color) => (left: RBMap<unknown, unknown>) => (k: unknown) => (v: unknown) => (right: RBMap<unknown, unknown>) => (() => {
  const _ll_s = c;
  if (_ll_s?._tag === `Red`) { return Node(Red, left, k, v, right); }
  if (_ll_s?._tag === `Black`) { return (() => {
  const _ll_s = left;
  if (_ll_s?._tag === `Node`) {  return ((result) => (() => {
  const _ll_s = result;
  if (_ll_s?._tag === `Node`) {  return result; }
  return ((((balanceRight)(left))(k))(v))(right);
  throw new Error(`Non-exhaustive match`);
})())(((((balanceLeft)(left))(k))(v))(right)); }
  return ((((balanceRight)(left))(k))(v))(right);
  throw new Error(`Non-exhaustive match`);
})(); }
  throw new Error(`Non-exhaustive match`);
})();

const ins = (cmp: unknown) => (k: unknown) => (v: unknown) => (m: RBMap<unknown, unknown>) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Leaf`) { return Node(Red, Leaf, k, v, Leaf); }
  if (_ll_s?._tag === `Node`) { const c = (_ll_s as Record<string, unknown>)[`_0`]; const left = (_ll_s as Record<string, unknown>)[`_1`]; const nk = (_ll_s as Record<string, unknown>)[`_2`]; const nv = (_ll_s as Record<string, unknown>)[`_3`]; const right = (_ll_s as Record<string, unknown>)[`_4`]; return ((d) => ((d < 0) ? (((((balance)(c))(((((ins)(cmp))(k))(v))(left)))(nk))(nv))(right) : ((d > 0) ? (((((balance)(c))(left))(nk))(nv))(((((ins)(cmp))(k))(v))(right)) : Node(c, left, nk, v, right))))(((cmp)(k))(nk)); }
  throw new Error(`Non-exhaustive match`);
})();

const mapInsert = (cmp: unknown) => (k: unknown) => (v: unknown) => (m: RBMap<unknown, unknown>) => ((t) => (() => {
  const _ll_s = t;
  if (_ll_s?._tag === `Leaf`) { return Leaf; }
  if (_ll_s?._tag === `Node`) { const left = (_ll_s as Record<string, unknown>)[`_1`]; const nk = (_ll_s as Record<string, unknown>)[`_2`]; const nv = (_ll_s as Record<string, unknown>)[`_3`]; const right = (_ll_s as Record<string, unknown>)[`_4`]; return Node(Black, left, nk, nv, right); }
  throw new Error(`Non-exhaustive match`);
})())(((((ins)(cmp))(k))(v))(m));

const mapLookup = (cmp: unknown) => (k: unknown) => (m: RBMap<unknown, unknown>) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Leaf`) { return None; }
  if (_ll_s?._tag === `Node`) { const left = (_ll_s as Record<string, unknown>)[`_1`]; const nk = (_ll_s as Record<string, unknown>)[`_2`]; const nv = (_ll_s as Record<string, unknown>)[`_3`]; const right = (_ll_s as Record<string, unknown>)[`_4`]; return ((d) => ((d < 0) ? (((mapLookup)(cmp))(k))(left) : ((d > 0) ? (((mapLookup)(cmp))(k))(right) : Some(nv))))(((cmp)(k))(nk)); }
  throw new Error(`Non-exhaustive match`);
})();

const mapContains = (cmp: unknown) => (k: unknown) => (m: RBMap<unknown, unknown>) => (() => {
  const _ll_s = (((mapLookup)(cmp))(k))(m);
  if (_ll_s?._tag === `Some`) {  return true; }
  if (_ll_s?._tag === `None`) { return false; }
  throw new Error(`Non-exhaustive match`);
})();

const mapFold = (f: unknown) => (acc: unknown) => (m: RBMap<unknown, unknown>) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Leaf`) { return acc; }
  if (_ll_s?._tag === `Node`) { const left = (_ll_s as Record<string, unknown>)[`_1`]; const k = (_ll_s as Record<string, unknown>)[`_2`]; const v = (_ll_s as Record<string, unknown>)[`_3`]; const right = (_ll_s as Record<string, unknown>)[`_4`]; return ((acc1) => ((acc2) => (((mapFold)(f))(acc2))(right))((((f)(acc1))(k))(v)))((((mapFold)(f))(acc))(left)); }
  throw new Error(`Non-exhaustive match`);
})();

const mapKeys = (m: RBMap<unknown, unknown>) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Leaf`) { return []; }
  if (_ll_s?._tag === `Node`) { const left = (_ll_s as Record<string, unknown>)[`_1`]; const k = (_ll_s as Record<string, unknown>)[`_2`]; const right = (_ll_s as Record<string, unknown>)[`_4`]; return ((lkeys) => ((rkeys) => ((listAppend)(lkeys))([k, ...rkeys]))((mapKeys)(right)))((mapKeys)(left)); }
  throw new Error(`Non-exhaustive match`);
})();

const intCmp = (a: number) => (b: number) => ((a < b) ? (0 - 1) : ((a > b) ? 1 : 0));

const strCmp = (a: string) => (b: string) => ((a < b) ? (0 - 1) : ((a > b) ? 1 : 0));

const mapCheck = (label: string) => (ok: boolean) => (ok ? ((_) => 0)((printfn)(((strConcat)(`OK `))(label))) : ((_) => 1)((printfn)(((strConcat)(`FAIL `))(label))));

const __ll_main_Std_Map = () => {};

const listTake = (n: number) => (xs: unknown[]) => ((n <= 0) ? [] : (() => {
  const _ll_s = xs;
  if (_ll_s.length >= 1) { const h = _ll_s[0]; const t = _ll_s.slice(1); return [h, ...((listTake)((n - 1)))(t)]; }
  if (_ll_s.length === 0) { return []; }
  throw new Error(`Non-exhaustive match`);
})());

const listDrop = (n: number) => (xs: unknown[]) => ((n <= 0) ? xs : (() => {
  const _ll_s = xs;
  if (_ll_s.length >= 1) { const t = _ll_s.slice(1); return ((listDrop)((n - 1)))(t); }
  if (_ll_s.length === 0) { return []; }
  throw new Error(`Non-exhaustive match`);
})());

const listFlatMap = (f: unknown) => (xs: unknown[]) => (listConcat)(((listMap)(f))(xs));

const listAny = (p: unknown) => (xs: unknown[]) => (((listFold)((acc: boolean) => (x: unknown) => (acc ? true : (p)(x))))(false))(xs);

const listAll = (p: unknown) => (xs: unknown[]) => (((listFold)((acc: boolean) => (x: unknown) => (acc ? (p)(x) : false)))(true))(xs);

const listFind = (p: unknown) => (xs: unknown[]) => (() => {
  const _ll_s = xs;
  if (_ll_s.length >= 1) { const h = _ll_s[0]; const t = _ll_s.slice(1); return ((p)(h) ? Some(h) : ((listFind)(p))(t)); }
  if (_ll_s.length === 0) { return None; }
  throw new Error(`Non-exhaustive match`);
})();

const listFindIndexFrom = (i: number) => (p: unknown) => (xs: unknown[]) => (() => {
  const _ll_s = xs;
  if (_ll_s.length >= 1) { const h = _ll_s[0]; const t = _ll_s.slice(1); return ((p)(h) ? Some(i) : (((listFindIndexFrom)((i + 1)))(p))(t)); }
  if (_ll_s.length === 0) { return None; }
  throw new Error(`Non-exhaustive match`);
})();

const listFindIndex = (p: unknown) => (xs: unknown[]) => (((listFindIndexFrom)(0))(p))(xs);

const listPartition = (p: unknown) => (xs: unknown[]) => ((foldedPair) => (() => {
  const _ll_s = foldedPair;
  { const ys = _ll_s[0]; const ns = _ll_s[1]; return [(listReverse)(ys), (listReverse)(ns)] as const; }
  throw new Error(`Non-exhaustive match`);
})())((((listFold)((acc: Tuple<unknown[], unknown[]>) => (x: unknown) => (() => {
  const _ll_s = acc;
  { const ys = _ll_s[0]; const ns = _ll_s[1]; return ((p)(x) ? [[x, ...ys], ns] as const : [ys, [x, ...ns]] as const); }
  throw new Error(`Non-exhaustive match`);
})()))([[], []] as const))(xs));

const check = (label: string) => (ok: boolean) => (ok ? ((_) => 0)((printfn)(((strConcat)(`OK `))(label))) : ((_) => 1)((printfn)(((strConcat)(`FAIL `))(label))));

const listCheck = (label: string) => (got: string) => (expected: string) => ((got === expected) ? (printfn)(((strConcat)(`OK `))(label)) : (printfn)(((strConcat)(`FAIL `))(((strConcat)(label))(((strConcat)(` expected=`))(((strConcat)(expected))(((strConcat)(` got=`))(got)))))));

const boolStr = (b: boolean) => (b ? `true` : `false`);

const showIntList = (xs: number[]) => ((strs) => (((listFold)((acc: string) => (s: string) => ((strConcat)(acc))(((strConcat)(`,`))(s))))(``))(strs))(((listMap)(intToStr))(xs));

const __ll_main_Std_List = () => {};

type Token = { _tag: `KwLet` } | { _tag: `KwTag` } | { _tag: `KwUnit` } | { _tag: `KwTrait` } | { _tag: `KwImpl` } | { _tag: `KwImport` } | { _tag: `KwExport` } | { _tag: `KwModule` } | { _tag: `KwExternal` } | { _tag: `KwOpaque` } | { _tag: `KwIf` } | { _tag: `KwElse` } | { _tag: `KwTrue` } | { _tag: `KwFalse` } | { _tag: `KwMatch` } | { _tag: `Ident`; _0: string } | { _tag: `TypeId`; _0: string } | { _tag: `IntLit`; _0: number } | { _tag: `FloatLit`; _0: string } | { _tag: `StrLit`; _0: string } | { _tag: `CharLit`; _0: string } | { _tag: `Arrow` } | { _tag: `Backslash` } | { _tag: `Dot` } | { _tag: `Comma` } | { _tag: `Colon` } | { _tag: `ColonColon` } | { _tag: `Eq` } | { _tag: `Bar` } | { _tag: `LBrack` } | { _tag: `RBrack` } | { _tag: `LParen` } | { _tag: `RParen` } | { _tag: `Plus` } | { _tag: `Minus` } | { _tag: `Star` } | { _tag: `Slash` } | { _tag: `Caret` } | { _tag: `Lt` } | { _tag: `Gt` } | { _tag: `Le` } | { _tag: `Ge` } | { _tag: `EqEq` } | { _tag: `Neq` } | { _tag: `Underscore` } | { _tag: `Newline` } | { _tag: `Indent` } | { _tag: `Dedent` } | { _tag: `Eof` } | { _tag: `TError`; _0: string };
const KwLet: Token = { _tag: `KwLet` as const };
const KwTag: Token = { _tag: `KwTag` as const };
const KwUnit: Token = { _tag: `KwUnit` as const };
const KwTrait: Token = { _tag: `KwTrait` as const };
const KwImpl: Token = { _tag: `KwImpl` as const };
const KwImport: Token = { _tag: `KwImport` as const };
const KwExport: Token = { _tag: `KwExport` as const };
const KwModule: Token = { _tag: `KwModule` as const };
const KwExternal: Token = { _tag: `KwExternal` as const };
const KwOpaque: Token = { _tag: `KwOpaque` as const };
const KwIf: Token = { _tag: `KwIf` as const };
const KwElse: Token = { _tag: `KwElse` as const };
const KwTrue: Token = { _tag: `KwTrue` as const };
const KwFalse: Token = { _tag: `KwFalse` as const };
const KwMatch: Token = { _tag: `KwMatch` as const };
const Ident = (_0: string): Token => ({ _tag: `Ident` as const, _0 });
const TypeId = (_0: string): Token => ({ _tag: `TypeId` as const, _0 });
const IntLit = (_0: number): Token => ({ _tag: `IntLit` as const, _0 });
const FloatLit = (_0: string): Token => ({ _tag: `FloatLit` as const, _0 });
const StrLit = (_0: string): Token => ({ _tag: `StrLit` as const, _0 });
const CharLit = (_0: string): Token => ({ _tag: `CharLit` as const, _0 });
const Arrow: Token = { _tag: `Arrow` as const };
const Backslash: Token = { _tag: `Backslash` as const };
const Dot: Token = { _tag: `Dot` as const };
const Comma: Token = { _tag: `Comma` as const };
const Colon: Token = { _tag: `Colon` as const };
const ColonColon: Token = { _tag: `ColonColon` as const };
const Eq: Token = { _tag: `Eq` as const };
const Bar: Token = { _tag: `Bar` as const };
const LBrack: Token = { _tag: `LBrack` as const };
const RBrack: Token = { _tag: `RBrack` as const };
const LParen: Token = { _tag: `LParen` as const };
const RParen: Token = { _tag: `RParen` as const };
const Plus: Token = { _tag: `Plus` as const };
const Minus: Token = { _tag: `Minus` as const };
const Star: Token = { _tag: `Star` as const };
const Slash: Token = { _tag: `Slash` as const };
const Caret: Token = { _tag: `Caret` as const };
const Lt: Token = { _tag: `Lt` as const };
const Gt: Token = { _tag: `Gt` as const };
const Le: Token = { _tag: `Le` as const };
const Ge: Token = { _tag: `Ge` as const };
const EqEq: Token = { _tag: `EqEq` as const };
const Neq: Token = { _tag: `Neq` as const };
const Underscore: Token = { _tag: `Underscore` as const };
const Newline: Token = { _tag: `Newline` as const };
const Indent: Token = { _tag: `Indent` as const };
const Dedent: Token = { _tag: `Dedent` as const };
const Eof: Token = { _tag: `Eof` as const };
const TError = (_0: string): Token => ({ _tag: `TError` as const, _0 });

const isUpperChar = (c: string) => ((n) => ((n < 65) ? false : ((n > 90) ? false : true)))((charToInt)(c));

const isLowerChar = (c: string) => ((n) => ((n < 97) ? false : ((n > 122) ? false : true)))((charToInt)(c));

const isIdStart = (c: string) => ((isUpperChar)(c) ? true : (isLowerChar)(c));

const isIdCont = (c: string) => ((isIdStart)(c) ? true : ((charIsDigit)(c) ? true : (c === `_`)));

const takeIdCont = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1) { const c = _ll_s[0]; const rest = _ll_s.slice(1); return ((isIdCont)(c) ? ((listAppend)([c]))((takeIdCont)(rest)) : []); }
  return [];
  throw new Error(`Non-exhaustive match`);
})();

const dropIdCont = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1) { const c = _ll_s[0]; const rest = _ll_s.slice(1); return ((isIdCont)(c) ? (dropIdCont)(rest) : cs); }
  return [];
  throw new Error(`Non-exhaustive match`);
})();

const takeDigit = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1) { const c = _ll_s[0]; const rest = _ll_s.slice(1); return ((charIsDigit)(c) ? ((listAppend)([c]))((takeDigit)(rest)) : []); }
  return [];
  throw new Error(`Non-exhaustive match`);
})();

const dropDigit = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1) { const c = _ll_s[0]; const rest = _ll_s.slice(1); return ((charIsDigit)(c) ? (dropDigit)(rest) : cs); }
  return [];
  throw new Error(`Non-exhaustive match`);
})();

const classifyIdent = (s: string) => (() => {
  const _ll_s = s;
  if (_ll_s === `let`) { return KwLet; }
  if (_ll_s === `tag`) { return KwTag; }
  if (_ll_s === `unit`) { return KwUnit; }
  if (_ll_s === `trait`) { return KwTrait; }
  if (_ll_s === `impl`) { return KwImpl; }
  if (_ll_s === `import`) { return KwImport; }
  if (_ll_s === `export`) { return KwExport; }
  if (_ll_s === `module`) { return KwModule; }
  if (_ll_s === `external`) { return KwExternal; }
  if (_ll_s === `opaque`) { return KwOpaque; }
  if (_ll_s === `if`) { return KwIf; }
  if (_ll_s === `else`) { return KwElse; }
  if (_ll_s === `true`) { return KwTrue; }
  if (_ll_s === `false`) { return KwFalse; }
  if (_ll_s === `match`) { return KwMatch; }
  return ((cs) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1) { const c = _ll_s[0]; return ((isUpperChar)(c) ? TypeId(s) : Ident(s)); }
  return Ident(s);
  throw new Error(`Non-exhaustive match`);
})())((strChars)(s));
  throw new Error(`Non-exhaustive match`);
})();

const parseIntStr = (s: string) => (() => {
  const _ll_s = (strToInt)(s);
  if (_ll_s?._tag === `Some`) { const n = (_ll_s as Record<string, unknown>)[`_0`]; return n; }
  if (_ll_s?._tag === `None`) { return 0; }
  throw new Error(`Non-exhaustive match`);
})();

const lexId = (cs: string[]) => ((idChars) => ((leftover) => ((tok) => ((listAppend)([tok]))((lexChars)(leftover)))((classifyIdent)((strFromChars)(idChars))))((dropIdCont)(cs)))((takeIdCont)(cs));

const lexNum = (cs: string[]) => ((digits) => ((rest0) => (() => {
  const _ll_s = rest0;
  if (_ll_s.length >= 2 && _ll_s[0] === `.`) { const c2 = _ll_s[1]; const rest1 = _ll_s.slice(2); return ((charIsDigit)(c2) ? ((fracDigits) => ((rest2) => ((intPart) => ((fracPart) => ((floatStr) => ((listAppend)([FloatLit(floatStr)]))((lexChars)(rest2)))(((strConcat)(((strConcat)(intPart))(`.`)))(fracPart)))((strFromChars)(fracDigits)))((strFromChars)(digits)))((dropDigit)([c2, ...rest1])))((takeDigit)([c2, ...rest1])) : ((n) => ((listAppend)([IntLit(n)]))((lexChars)(rest0)))((parseIntStr)((strFromChars)(digits)))); }
  return ((n) => ((listAppend)([IntLit(n)]))((lexChars)(rest0)))((parseIntStr)((strFromChars)(digits)));
  throw new Error(`Non-exhaustive match`);
})())((dropDigit)(cs)))((takeDigit)(cs));

const takeStrBody = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length === 0) { return [[], []] as const; }
  if (_ll_s.length >= 1) { const c = _ll_s[0]; const rest = _ll_s.slice(1); return ((c === `"`) ? [[], rest] as const : ((c === `\\`) ? (takeStrBodyEsc)(rest) : ((pair) => (() => {
  const _ll_s = pair;
  { const body = _ll_s[0]; const leftover = _ll_s[1]; return [[c, ...body], leftover] as const; }
  throw new Error(`Non-exhaustive match`);
})())((takeStrBody)(rest)))); }
  throw new Error(`Non-exhaustive match`);
})();

const takeStrBodyEsc = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length === 0) { return [[], []] as const; }
  if (_ll_s.length >= 1) { const esc = _ll_s[0]; const rest = _ll_s.slice(1); return ((pair) => (() => {
  const _ll_s = pair;
  { const body = _ll_s[0]; const leftover = _ll_s[1]; return [[(decodeEscape)(esc), ...body], leftover] as const; }
  throw new Error(`Non-exhaustive match`);
})())((takeStrBody)(rest)); }
  throw new Error(`Non-exhaustive match`);
})();

const decodeEscape = (c: string) => (() => {
  const _ll_s = c;
  if (_ll_s === `n`) { return `\n`; }
  if (_ll_s === `t`) { return `\t`; }
  if (_ll_s === `r`) { return `\r`; }
  if (_ll_s === `\\`) { return `\\`; }
  if (_ll_s === `'`) { return `'`; }
  if (_ll_s === `"`) { return `"`; }
  if (_ll_s === `0`) { return `\0`; }
  return c;
  throw new Error(`Non-exhaustive match`);
})();

const lexStr = (cs: string[]) => ((pair) => (() => {
  const _ll_s = pair;
  { const body = _ll_s[0]; const leftover = _ll_s[1]; return ((listAppend)([StrLit((strFromChars)(body))]))((lexChars)(leftover)); }
  throw new Error(`Non-exhaustive match`);
})())((takeStrBody)(cs));

const lexCharLit = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length === 0) { return [Eof]; }
  if (_ll_s.length >= 1) { const ch = _ll_s[0]; const rest = _ll_s.slice(1); return ((ch === `\\`) ? (() => {
  const _ll_s = rest;
  if (_ll_s.length === 0) { return [Eof]; }
  if (_ll_s.length >= 1) { const esc = _ll_s[0]; const rest2 = _ll_s.slice(1); return (() => {
  const _ll_s = rest2;
  if (_ll_s.length >= 1 && _ll_s[0] === `'`) { const rest3 = _ll_s.slice(1); return ((listAppend)([CharLit((decodeEscape)(esc))]))((lexChars)(rest3)); }
  return (lexChars)(cs);
  throw new Error(`Non-exhaustive match`);
})(); }
  throw new Error(`Non-exhaustive match`);
})() : (() => {
  const _ll_s = rest;
  if (_ll_s.length >= 1 && _ll_s[0] === `'`) { const rest2 = _ll_s.slice(1); return ((listAppend)([CharLit(ch)]))((lexChars)(rest2)); }
  return (lexChars)(cs);
  throw new Error(`Non-exhaustive match`);
})()); }
  throw new Error(`Non-exhaustive match`);
})();

const skipLineComment = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length === 0) { return [Eof]; }
  if (_ll_s.length >= 1) { const c = _ll_s[0]; const rest = _ll_s.slice(1); return ((c === `\n`) ? ((listAppend)([Newline]))((lexChars)(rest)) : (skipLineComment)(rest)); }
  throw new Error(`Non-exhaustive match`);
})();

const lexEqOrEqEq = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1 && _ll_s[0] === `=`) { const rest = _ll_s.slice(1); return ((listAppend)([EqEq]))((lexChars)(rest)); }
  return ((listAppend)([Eq]))((lexChars)(cs));
  throw new Error(`Non-exhaustive match`);
})();

const lexNeq = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1 && _ll_s[0] === `=`) { const rest = _ll_s.slice(1); return ((listAppend)([Neq]))((lexChars)(rest)); }
  return (lexChars)(cs);
  throw new Error(`Non-exhaustive match`);
})();

const lexLtOrLe = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1 && _ll_s[0] === `=`) { const rest = _ll_s.slice(1); return ((listAppend)([Le]))((lexChars)(rest)); }
  return ((listAppend)([Lt]))((lexChars)(cs));
  throw new Error(`Non-exhaustive match`);
})();

const lexGtOrGe = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1 && _ll_s[0] === `=`) { const rest = _ll_s.slice(1); return ((listAppend)([Ge]))((lexChars)(rest)); }
  return ((listAppend)([Gt]))((lexChars)(cs));
  throw new Error(`Non-exhaustive match`);
})();

const lexMinusOrArrow = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1 && _ll_s[0] === `>`) { const rest = _ll_s.slice(1); return ((listAppend)([Arrow]))((lexChars)(rest)); }
  if (_ll_s.length >= 1 && _ll_s[0] === `-`) { const rest = _ll_s.slice(1); return (skipLineComment)(rest); }
  return ((listAppend)([Minus]))((lexChars)(cs));
  throw new Error(`Non-exhaustive match`);
})();

const lexColonOrCons = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1 && _ll_s[0] === `:`) { const rest = _ll_s.slice(1); return ((listAppend)([ColonColon]))((lexChars)(rest)); }
  return ((listAppend)([Colon]))((lexChars)(cs));
  throw new Error(`Non-exhaustive match`);
})();

const lexUnderOrIdent = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length >= 1) { const c = _ll_s[0]; return ((isIdCont)(c) ? ((idChars) => ((leftover) => ((tok) => ((listAppend)([tok]))((lexChars)(leftover)))((classifyIdent)((strFromChars)(idChars))))((dropIdCont)(cs)))(((listAppend)([`_`]))((takeIdCont)(cs))) : ((listAppend)([Underscore]))((lexChars)(cs))); }
  return ((listAppend)([Underscore]))((lexChars)(cs));
  throw new Error(`Non-exhaustive match`);
})();

const lexChars = (cs: string[]) => (() => {
  const _ll_s = cs;
  if (_ll_s.length === 0) { return [Eof]; }
  if (_ll_s.length >= 1) { const c = _ll_s[0]; const rest = _ll_s.slice(1); return ((c === `\n`) ? ((listAppend)([Newline]))((lexChars)(rest)) : ((charIsSpace)(c) ? (lexChars)(rest) : ((c === `-`) ? (lexMinusOrArrow)(rest) : ((isIdStart)(c) ? (lexId)(cs) : ((c === `_`) ? (lexUnderOrIdent)(rest) : ((charIsDigit)(c) ? (lexNum)(cs) : ((c === `"`) ? (lexStr)(rest) : ((c === `'`) ? (lexCharLit)(rest) : ((c === `=`) ? (lexEqOrEqEq)(rest) : ((c === `!`) ? (lexNeq)(rest) : ((c === `<`) ? (lexLtOrLe)(rest) : ((c === `>`) ? (lexGtOrGe)(rest) : ((c === `:`) ? (lexColonOrCons)(rest) : ((c === `(`) ? ((listAppend)([LParen]))((lexChars)(rest)) : ((c === `)`) ? ((listAppend)([RParen]))((lexChars)(rest)) : ((c === `[`) ? ((listAppend)([LBrack]))((lexChars)(rest)) : ((c === `]`) ? ((listAppend)([RBrack]))((lexChars)(rest)) : ((c === `|`) ? ((listAppend)([Bar]))((lexChars)(rest)) : ((c === `+`) ? ((listAppend)([Plus]))((lexChars)(rest)) : ((c === `*`) ? ((listAppend)([Star]))((lexChars)(rest)) : ((c === `/`) ? ((listAppend)([Slash]))((lexChars)(rest)) : ((c === `^`) ? ((listAppend)([Caret]))((lexChars)(rest)) : ((c === `.`) ? ((listAppend)([Dot]))((lexChars)(rest)) : ((c === `,`) ? ((listAppend)([Comma]))((lexChars)(rest)) : ((c === `\\`) ? ((listAppend)([Backslash]))((lexChars)(rest)) : ((listAppend)([TError(c)]))((lexChars)(rest))))))))))))))))))))))))))); }
  throw new Error(`Non-exhaustive match`);
})();

const tokenize = (src: string) => (lexChars)((strChars)(src));

const showToken = (t: Token) => (() => {
  const _ll_s = t;
  if (_ll_s?._tag === `KwLet`) { return `KwLet`; }
  if (_ll_s?._tag === `KwTag`) { return `KwTag`; }
  if (_ll_s?._tag === `KwUnit`) { return `KwUnit`; }
  if (_ll_s?._tag === `KwTrait`) { return `KwTrait`; }
  if (_ll_s?._tag === `KwImpl`) { return `KwImpl`; }
  if (_ll_s?._tag === `KwImport`) { return `KwImport`; }
  if (_ll_s?._tag === `KwExport`) { return `KwExport`; }
  if (_ll_s?._tag === `KwModule`) { return `KwModule`; }
  if (_ll_s?._tag === `KwIf`) { return `KwIf`; }
  if (_ll_s?._tag === `KwElse`) { return `KwElse`; }
  if (_ll_s?._tag === `KwTrue`) { return `KwTrue`; }
  if (_ll_s?._tag === `KwFalse`) { return `KwFalse`; }
  if (_ll_s?._tag === `KwMatch`) { return `KwMatch`; }
  if (_ll_s?._tag === `Ident`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`Ident:`))(s); }
  if (_ll_s?._tag === `TypeId`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`TypeId:`))(s); }
  if (_ll_s?._tag === `IntLit`) { const n = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`Int:`))((intToStr)(n)); }
  if (_ll_s?._tag === `FloatLit`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`Float:`))(s); }
  if (_ll_s?._tag === `StrLit`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`Str:`))(s); }
  if (_ll_s?._tag === `CharLit`) { const c = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`Char:`))((strFromChars)([c])); }
  if (_ll_s?._tag === `Arrow`) { return `Arrow`; }
  if (_ll_s?._tag === `Backslash`) { return `Backslash`; }
  if (_ll_s?._tag === `Dot`) { return `Dot`; }
  if (_ll_s?._tag === `Comma`) { return `Comma`; }
  if (_ll_s?._tag === `Colon`) { return `Colon`; }
  if (_ll_s?._tag === `ColonColon`) { return `ColonColon`; }
  if (_ll_s?._tag === `Eq`) { return `Eq`; }
  if (_ll_s?._tag === `Bar`) { return `Bar`; }
  if (_ll_s?._tag === `LBrack`) { return `LBrack`; }
  if (_ll_s?._tag === `RBrack`) { return `RBrack`; }
  if (_ll_s?._tag === `LParen`) { return `LParen`; }
  if (_ll_s?._tag === `RParen`) { return `RParen`; }
  if (_ll_s?._tag === `Plus`) { return `Plus`; }
  if (_ll_s?._tag === `Minus`) { return `Minus`; }
  if (_ll_s?._tag === `Star`) { return `Star`; }
  if (_ll_s?._tag === `Slash`) { return `Slash`; }
  if (_ll_s?._tag === `Caret`) { return `Caret`; }
  if (_ll_s?._tag === `Lt`) { return `Lt`; }
  if (_ll_s?._tag === `Gt`) { return `Gt`; }
  if (_ll_s?._tag === `Le`) { return `Le`; }
  if (_ll_s?._tag === `Ge`) { return `Ge`; }
  if (_ll_s?._tag === `EqEq`) { return `EqEq`; }
  if (_ll_s?._tag === `Neq`) { return `Neq`; }
  if (_ll_s?._tag === `Underscore`) { return `Underscore`; }
  if (_ll_s?._tag === `Newline`) { return `Newline`; }
  if (_ll_s?._tag === `Indent`) { return `Indent`; }
  if (_ll_s?._tag === `Dedent`) { return `Dedent`; }
  if (_ll_s?._tag === `Eof`) { return `Eof`; }
  if (_ll_s?._tag === `TError`) { const c = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`Error:`))((strFromChars)([c])); }
  throw new Error(`Non-exhaustive match`);
})();

const showTokens = (ts: Token[]) => (((listFold)((acc: string) => (t: Token) => ((s) => (((strLen)(acc) === 0) ? s : ((strConcat)(((strConcat)(acc))(` `)))(s)))((showToken)(t))))(``))(ts);

const stripNewlines = (ts: Token[]) => (() => {
  const _ll_s = ts;
  if (_ll_s.length === 0) { return []; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Newline`) { const rest = _ll_s.slice(1); return (stripNewlines)(rest); }
  if (_ll_s.length >= 1) { const t = _ll_s[0]; const rest = _ll_s.slice(1); return [t, ...(stripNewlines)(rest)]; }
  throw new Error(`Non-exhaustive match`);
})();

const checkTokens = (label: string) => (src: string) => (expected: string) => ((got) => ((got === expected) ? (printfn)(((strConcat)(`OK `))(label)) : ((p1) => ((p2) => ((p3) => ((p4) => ((p5) => (printfn)(p5))(((strConcat)(p4))(got)))(((strConcat)(p3))(`\n  got:      `)))(((strConcat)(p2))(expected)))(((strConcat)(p1))(`\n  expected: `)))(((strConcat)(`FAIL `))(label))))((showTokens)((stripNewlines)((tokenize)(src))));

const __ll_main_Std_Lexer = () => {};

type Pattern = { _tag: `PVar`; _0: string } | { _tag: `PWild` } | { _tag: `PCon`; _0: string; _1: Pattern[] } | { _tag: `PLitInt`; _0: number } | { _tag: `PLitStr`; _0: string } | { _tag: `PCons`; _0: Pattern; _1: Pattern } | { _tag: `PNil` };
const PVar = (_0: string): Pattern => ({ _tag: `PVar` as const, _0 });
const PWild: Pattern = { _tag: `PWild` as const };
const PCon = (_0: string, _1: Pattern[]): Pattern => ({ _tag: `PCon` as const, _0, _1 });
const PLitInt = (_0: number): Pattern => ({ _tag: `PLitInt` as const, _0 });
const PLitStr = (_0: string): Pattern => ({ _tag: `PLitStr` as const, _0 });
const PCons = (_0: Pattern, _1: Pattern): Pattern => ({ _tag: `PCons` as const, _0, _1 });
const PNil: Pattern = { _tag: `PNil` as const };

type Expr = { _tag: `EInt`; _0: number } | { _tag: `EStr`; _0: string } | { _tag: `EBool`; _0: boolean } | { _tag: `EChar`; _0: string } | { _tag: `EFloat`; _0: string } | { _tag: `EVar`; _0: string } | { _tag: `ECon`; _0: string } | { _tag: `EApp`; _0: Expr; _1: Expr } | { _tag: `EIf`; _0: Expr; _1: Expr; _2: Expr } | { _tag: `EMatch`; _0: Expr; _1: Pattern[]; _2: Expr[] } | { _tag: `ELam`; _0: string; _1: Expr } | { _tag: `ELet`; _0: string; _1: Expr; _2: Expr } | { _tag: `EList`; _0: Expr[] } | { _tag: `EBinOp`; _0: string; _1: Expr; _2: Expr } | { _tag: `ETuple`; _0: Expr; _1: Expr } | { _tag: `ENil` } | { _tag: `ECons`; _0: Expr; _1: Expr };
const EInt = (_0: number): Expr => ({ _tag: `EInt` as const, _0 });
const EStr = (_0: string): Expr => ({ _tag: `EStr` as const, _0 });
const EBool = (_0: boolean): Expr => ({ _tag: `EBool` as const, _0 });
const EChar = (_0: string): Expr => ({ _tag: `EChar` as const, _0 });
const EFloat = (_0: string): Expr => ({ _tag: `EFloat` as const, _0 });
const EVar = (_0: string): Expr => ({ _tag: `EVar` as const, _0 });
const ECon = (_0: string): Expr => ({ _tag: `ECon` as const, _0 });
const EApp = (_0: Expr, _1: Expr): Expr => ({ _tag: `EApp` as const, _0, _1 });
const EIf = (_0: Expr, _1: Expr, _2: Expr): Expr => ({ _tag: `EIf` as const, _0, _1, _2 });
const EMatch = (_0: Expr, _1: Pattern[], _2: Expr[]): Expr => ({ _tag: `EMatch` as const, _0, _1, _2 });
const ELam = (_0: string, _1: Expr): Expr => ({ _tag: `ELam` as const, _0, _1 });
const ELet = (_0: string, _1: Expr, _2: Expr): Expr => ({ _tag: `ELet` as const, _0, _1, _2 });
const EList = (_0: Expr[]): Expr => ({ _tag: `EList` as const, _0 });
const EBinOp = (_0: string, _1: Expr, _2: Expr): Expr => ({ _tag: `EBinOp` as const, _0, _1, _2 });
const ETuple = (_0: Expr, _1: Expr): Expr => ({ _tag: `ETuple` as const, _0, _1 });
const ENil: Expr = { _tag: `ENil` as const };
const ECons = (_0: Expr, _1: Expr): Expr => ({ _tag: `ECons` as const, _0, _1 });

type TypeExpr = { _tag: `TyName`; _0: string } | { _tag: `TyApp`; _0: TypeExpr; _1: TypeExpr } | { _tag: `TyFn`; _0: TypeExpr; _1: TypeExpr };
const TyName = (_0: string): TypeExpr => ({ _tag: `TyName` as const, _0 });
const TyApp = (_0: TypeExpr, _1: TypeExpr): TypeExpr => ({ _tag: `TyApp` as const, _0, _1 });
const TyFn = (_0: TypeExpr, _1: TypeExpr): TypeExpr => ({ _tag: `TyFn` as const, _0, _1 });

type Param = { _tag: `MkParam`; _0: string; _1: TypeExpr };
const MkParam = (_0: string, _1: TypeExpr): Param => ({ _tag: `MkParam` as const, _0, _1 });

type Constructor = { _tag: `MkCon`; _0: string; _1: TypeExpr[] };
const MkCon = (_0: string, _1: TypeExpr[]): Constructor => ({ _tag: `MkCon` as const, _0, _1 });

type Decl = { _tag: `DFn`; _0: string; _1: Param[]; _2: TypeExpr | null; _3: Expr } | { _tag: `DType`; _0: string; _1: string[]; _2: Constructor[] } | { _tag: `DImport`; _0: string[] } | { _tag: `DImportUrl`; _0: string } | { _tag: `DExport`; _0: Decl } | { _tag: `DLet`; _0: string; _1: Expr } | { _tag: `DExternal`; _0: string; _1: Param[]; _2: TypeExpr } | { _tag: `DOpaque`; _0: string };
const DFn = (_0: string, _1: Param[], _2: TypeExpr | null, _3: Expr): Decl => ({ _tag: `DFn` as const, _0, _1, _2, _3 });
const DType = (_0: string, _1: string[], _2: Constructor[]): Decl => ({ _tag: `DType` as const, _0, _1, _2 });
const DImport = (_0: string[]): Decl => ({ _tag: `DImport` as const, _0 });
const DImportUrl = (_0: string): Decl => ({ _tag: `DImportUrl` as const, _0 });
const DExport = (_0: Decl): Decl => ({ _tag: `DExport` as const, _0 });
const DLet = (_0: string, _1: Expr): Decl => ({ _tag: `DLet` as const, _0, _1 });
const DExternal = (_0: string, _1: Param[], _2: TypeExpr): Decl => ({ _tag: `DExternal` as const, _0, _1, _2 });
const DOpaque = (_0: string): Decl => ({ _tag: `DOpaque` as const, _0 });

type Module = { _tag: `MkModule`; _0: string[]; _1: Decl[] };
const MkModule = (_0: string[], _1: Decl[]): Module => ({ _tag: `MkModule` as const, _0, _1 });

const skipNewlines = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Newline`) { const rest = _ll_s.slice(1); return (skipNewlines)(rest); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Indent`) { const rest = _ll_s.slice(1); return (skipNewlines)(rest); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Dedent`) { const rest = _ll_s.slice(1); return (skipNewlines)(rest); }
  return toks;
  throw new Error(`Non-exhaustive match`);
})();

const isAtomStart = (t: Token) => (() => {
  const _ll_s = t;
  if (_ll_s?._tag === `IntLit`) {  return true; }
  if (_ll_s?._tag === `FloatLit`) {  return true; }
  if (_ll_s?._tag === `StrLit`) {  return true; }
  if (_ll_s?._tag === `CharLit`) {  return true; }
  if (_ll_s?._tag === `KwTrue`) { return true; }
  if (_ll_s?._tag === `KwFalse`) { return true; }
  if (_ll_s?._tag === `Ident`) {  return true; }
  if (_ll_s?._tag === `TypeId`) {  return true; }
  if (_ll_s?._tag === `LParen`) { return true; }
  if (_ll_s?._tag === `LBrack`) { return true; }
  return false;
  throw new Error(`Non-exhaustive match`);
})();

const skipBrackTypeArgs = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `LBrack`) { const rest = _ll_s.slice(1); return ((rest2) => (skipBrackTypeArgs)(rest2))((skipBrackTypeBody)(rest)); }
  return toks;
  throw new Error(`Non-exhaustive match`);
})();

const skipBrackTypeBody = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `RBrack`) { const rest = _ll_s.slice(1); return rest; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `LBrack`) { const rest = _ll_s.slice(1); return ((rest2) => (skipBrackTypeBody)(rest2))((skipBrackTypeBody)(rest)); }
  if (_ll_s.length >= 1) { const rest = _ll_s.slice(1); return (skipBrackTypeBody)(rest); }
  if (_ll_s.length === 0) { return []; }
  throw new Error(`Non-exhaustive match`);
})();

const parseTypeExprAtom = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return ((rest2) => [TyName(name), rest2] as const)((skipBrackTypeArgs)(rest)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [TyName(name), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `LParen`) { const rest = _ll_s.slice(1); return (parseTypeExprParens)(rest); }
  return [TyName(`?`), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseTypeExprParens = (toks: Token[]) => (([head, rest]) => ((parseTypeExprParensTail)(head))(rest))((parseTypeExprAtom)(toks));

const parseTypeExprParensTail = (acc: TypeExpr) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { return (([next, rest]) => ((parseTypeExprParensTail)(TyApp(acc, next)))(rest))((parseTypeExprAtom)(toks)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { return (([next, rest]) => ((parseTypeExprParensTail)(TyApp(acc, next)))(rest))((parseTypeExprAtom)(toks)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `LParen`) { return (([next, rest]) => ((parseTypeExprParensTail)(TyApp(acc, next)))(rest))((parseTypeExprAtom)(toks)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `RParen`) { const rest = _ll_s.slice(1); return [acc, rest] as const; }
  return [acc, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseTypeExpr = (toks: Token[]) => (parseTypeExprAtom)(toks);

const parseReturnType = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return ((rest2) => [Some(TyName(name)), rest2] as const)((skipBrackTypeArgs)(rest)); }
  return [None, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseParamGroups = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `LParen` && _ll_s[1]?._tag === `RParen`) { const rest = _ll_s.slice(2); return [[], rest] as const; }
  if (_ll_s.length >= 3 && _ll_s[0]?._tag === `LParen` && _ll_s[1]?._tag === `Ident` && _ll_s[2]?._tag === `TypeId`) { const pname = (_ll_s[1] as Record<string, unknown>)[`_0`]; const tname = (_ll_s[2] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(3); return ((rest2) => ((rest3) => (([ps, rest4]) => [[MkParam(pname, TyName(tname)), ...ps], rest4] as const)((parseParamGroups)(rest3)))((() => {
  const _ll_s = rest2;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `RParen`) { const r = _ll_s.slice(1); return r; }
  return rest2;
  throw new Error(`Non-exhaustive match`);
})()))((skipBrackTypeArgs)(rest)); }
  if (_ll_s.length >= 4 && _ll_s[0]?._tag === `LParen` && _ll_s[1]?._tag === `Underscore` && _ll_s[2]?._tag === `Ident` && _ll_s[3]?._tag === `TypeId`) { const pname = (_ll_s[2] as Record<string, unknown>)[`_0`]; const tname = (_ll_s[3] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(4); return ((rest2) => ((rest3) => (([ps, rest4]) => [[MkParam(((strConcat)(`_`))(pname), TyName(tname)), ...ps], rest4] as const)((parseParamGroups)(rest3)))((() => {
  const _ll_s = rest2;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `RParen`) { const r = _ll_s.slice(1); return r; }
  return rest2;
  throw new Error(`Non-exhaustive match`);
})()))((skipBrackTypeArgs)(rest)); }
  if (_ll_s.length >= 3 && _ll_s[0]?._tag === `LParen` && _ll_s[1]?._tag === `Ident` && _ll_s[2]?._tag === `RParen`) { const pname = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(3); return (([ps, rest2]) => [[MkParam(pname, TyName(`?`)), ...ps], rest2] as const)((parseParamGroups)(rest)); }
  return [[], toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseTypeParams = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { const s = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return (((strLen)(s) === 1) ? (([ps, rest2]) => [[s, ...ps], rest2] as const)((parseTypeParams)(rest)) : [[], toks] as const); }
  return [[], toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseConArgs = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { return (([arg, rest]) => (([args, rest2]) => [[arg, ...args], rest2] as const)((parseConArgs)(rest)))((parseTypeExprAtom)(toks)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `LParen`) { return (([arg, rest]) => (([args, rest2]) => [[arg, ...args], rest2] as const)((parseConArgs)(rest)))((parseTypeExprAtom)(toks)); }
  return [[], toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseCon = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return (([args, rest2]) => [MkCon(name, args), rest2] as const)((parseConArgs)(rest)); }
  return [MkCon(`?`, []), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseConsTail = (acc: Constructor[]) => (toks: Token[]) => ((toks2) => (() => {
  const _ll_s = toks2;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Bar`) { const rest = _ll_s.slice(1); return ((rest2) => (([c, rest3]) => ((parseConsTail)(((listAppend)(acc))([c])))(rest3))((parseCon)(rest2)))((skipNewlines)(rest)); }
  return [acc, toks] as const;
  throw new Error(`Non-exhaustive match`);
})())((skipNewlines)(toks));

const parseConList = (toks: Token[]) => ((toks2) => ((toks3) => (([c, rest]) => ((parseConsTail)([c]))(rest))((parseCon)(toks3)))((() => {
  const _ll_s = toks2;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Bar`) { const r = _ll_s.slice(1); return (skipNewlines)(r); }
  return toks2;
  throw new Error(`Non-exhaustive match`);
})()))((skipNewlines)(toks));

const parseTypeDecl = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return (([prms, rest2]) => ((rest3) => (([ctors, rest4]) => [DType(name, prms, ctors), rest4] as const)((parseConList)(rest3)))((() => {
  const _ll_s = (skipNewlines)(rest2);
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Eq`) { const r = _ll_s.slice(1); return (skipNewlines)(r); }
  return (skipNewlines)(rest2);
  throw new Error(`Non-exhaustive match`);
})()))((parseTypeParams)(rest)); }
  return [DType(`?`, [], []), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parsePrimaryPat = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `IntLit`) { const n = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [PLitInt(n), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `StrLit`) { const s = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [PLitStr(s), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Underscore`) { const rest = _ll_s.slice(1); return [PWild, rest] as const; }
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `LBrack` && _ll_s[1]?._tag === `RBrack`) { const rest = _ll_s.slice(2); return [PNil, rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { const s = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [PVar(s), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return (([args, rest2]) => [PCon(name, args), rest2] as const)((parsePatArgs)(rest)); }
  return [PWild, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parsePatArgs = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { return (parsePatArgsCons)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Underscore`) { return (parsePatArgsCons)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `IntLit`) { return (parsePatArgsCons)(toks); }
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `LBrack` && _ll_s[1]?._tag === `RBrack`) { return (parsePatArgsCons)(toks); }
  return [[], toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parsePatArgsCons = (toks: Token[]) => (([p, rest]) => (([ps, rest2]) => [((listAppend)([p]))(ps), rest2] as const)((parsePatArgs)(rest)))((parsePrimaryPat)(toks));

const parsePat = (toks: Token[]) => (([p, rest]) => (() => {
  const _ll_s = rest;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `ColonColon`) { const rest2 = _ll_s.slice(1); return (([tail, rest3]) => [PCons(p, tail), rest3] as const)((parsePat)(rest2)); }
  return [p, rest] as const;
  throw new Error(`Non-exhaustive match`);
})())((parsePrimaryPat)(toks));

const parseArmBody = (toks: Token[]) => ((toks2) => (() => {
  const _ll_s = toks2;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwIf`) { const rest = _ll_s.slice(1); return (parseIf)(rest); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwLet`) { const rest = _ll_s.slice(1); return (parseLetIn)(rest); }
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `Ident` && _ll_s[1]?._tag === `Eq`) { return (parseLetIn)(toks2); }
  return (parseCompare)(toks2);
  throw new Error(`Non-exhaustive match`);
})())((skipNewlines)(toks));

const skipArrow = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Arrow`) { const r = _ll_s.slice(1); return r; }
  return toks;
  throw new Error(`Non-exhaustive match`);
})();

const parseArm = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Bar`) { const rest = _ll_s.slice(1); return (([p, rest2]) => ((rest3) => (([body, rest4]) => [[p, body] as const, rest4] as const)((parseArmBody)(rest3)))((skipArrow)(rest2)))((parsePat)(rest)); }
  return [[PWild, EInt(0)] as const, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseArms = (toks: Token[]) => ((toks2) => (() => {
  const _ll_s = toks2;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Bar`) { return (([pb, rest]) => (([p, b]) => (([morePB, rest2]) => (([ps, bs]) => [[[p, ...ps], [b, ...bs]] as const, rest2] as const)(morePB))((parseArms)(rest)))(pb))((parseArm)(toks2)); }
  return [[[], []] as const, toks2] as const;
  throw new Error(`Non-exhaustive match`);
})())((skipNewlines)(toks));

const parseMatch = (toks: Token[]) => (([scrut, rest]) => (([armLists, rest2]) => (([pats, bodies]) => [EMatch(scrut, pats, bodies), rest2] as const)(armLists))((parseArms)(rest)))((parseExpr)(toks));

const parseIf = (toks: Token[]) => (([cond, rest]) => ((rest2) => (([thenE, rest3]) => ((rest3a) => ((rest4) => (([elseE, rest5]) => [EIf(cond, thenE, elseE), rest5] as const)((parseExpr)(rest4)))((() => {
  const _ll_s = rest3a;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwElse`) { const r = _ll_s.slice(1); return (skipNewlines)(r); }
  return rest3a;
  throw new Error(`Non-exhaustive match`);
})()))((skipNewlines)(rest3)))((parseExpr)(rest2)))((skipNewlines)(rest)))((parseExpr)(toks));

const skipKwIn = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwLet`) { const r = _ll_s.slice(1); return (skipNewlines)(r); }
  return (skipNewlines)(toks);
  throw new Error(`Non-exhaustive match`);
})();

const parseLetIn = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 6 && _ll_s[0]?._tag === `LParen` && _ll_s[1]?._tag === `Ident` && _ll_s[2]?._tag === `Comma` && _ll_s[3]?._tag === `Ident` && _ll_s[4]?._tag === `RParen` && _ll_s[5]?._tag === `Eq`) { const a = (_ll_s[1] as Record<string, unknown>)[`_0`]; const b = (_ll_s[3] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(6); return ((rest0) => (([e1, rest2]) => ((rest3) => (([e2, rest4]) => [ELet(a, e1, ELet(b, ETuple(e1, e2), e2)), rest4] as const)((parseExpr)(rest3)))((skipKwIn)(rest2)))((parseExpr)(rest0)))((skipNewlines)(rest)); }
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `Ident` && _ll_s[1]?._tag === `Eq`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(2); return ((rest0) => (([e1, rest2]) => ((rest3) => (([e2, rest4]) => [ELet(name, e1, e2), rest4] as const)((parseExpr)(rest3)))((skipKwIn)(rest2)))((parseExpr)(rest0)))((skipNewlines)(rest)); }
  return [EInt(0), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseLamParams = (acc: string[]) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return ((parseLamParams)(((listAppend)(acc))([name])))(rest); }
  return [acc, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const wrapLamParams = (parms: string[]) => (body: Expr) => (() => {
  const _ll_s = parms;
  if (_ll_s.length >= 1) { const p = _ll_s[0]; const rest = _ll_s.slice(1); return ELam(p, ((wrapLamParams)(rest))(body)); }
  return body;
  throw new Error(`Non-exhaustive match`);
})();

const parseLam = (toks: Token[]) => (([parms, rest]) => (() => {
  const _ll_s = rest;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Dot`) { const rest2 = _ll_s.slice(1); return (([body, rest3]) => [((wrapLamParams)(parms))(body), rest3] as const)((parseExpr)(rest2)); }
  return [EInt(0), toks] as const;
  throw new Error(`Non-exhaustive match`);
})())(((parseLamParams)([]))(toks));

const parseExpr = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwIf`) { const rest = _ll_s.slice(1); return (parseIf)(rest); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwMatch`) { const rest = _ll_s.slice(1); return (parseMatch)(rest); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwLet`) { const rest = _ll_s.slice(1); return (parseLetIn)(rest); }
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `Ident` && _ll_s[1]?._tag === `Eq`) { return (parseLetIn)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Backslash`) { const rest = _ll_s.slice(1); return (parseLam)(rest); }
  return (parseCompare)(toks);
  throw new Error(`Non-exhaustive match`);
})();

const parseCompare = (toks: Token[]) => (([e, rest]) => ((parseCompareTail)(e))(rest))((parseCons)(toks));

const parseCompareTail = (lhs: Expr) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `EqEq`) { const r = _ll_s.slice(1); return (([rhs, rest2]) => ((parseCompareTail)(EBinOp(`==`, lhs, rhs)))(rest2))((parseCons)(r)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Neq`) { const r = _ll_s.slice(1); return (([rhs, rest2]) => ((parseCompareTail)(EBinOp(`!=`, lhs, rhs)))(rest2))((parseCons)(r)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Lt`) { const r = _ll_s.slice(1); return (([rhs, rest2]) => ((parseCompareTail)(EBinOp(`<`, lhs, rhs)))(rest2))((parseCons)(r)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Gt`) { const r = _ll_s.slice(1); return (([rhs, rest2]) => ((parseCompareTail)(EBinOp(`>`, lhs, rhs)))(rest2))((parseCons)(r)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Le`) { const r = _ll_s.slice(1); return (([rhs, rest2]) => ((parseCompareTail)(EBinOp(`<=`, lhs, rhs)))(rest2))((parseCons)(r)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ge`) { const r = _ll_s.slice(1); return (([rhs, rest2]) => ((parseCompareTail)(EBinOp(`>=`, lhs, rhs)))(rest2))((parseCons)(r)); }
  return [lhs, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseCons = (toks: Token[]) => (([head, rest]) => (() => {
  const _ll_s = rest;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `ColonColon`) { const rest2 = _ll_s.slice(1); return (([tail, rest3]) => [ECons(head, tail), rest3] as const)((parseCons)(rest2)); }
  return [head, rest] as const;
  throw new Error(`Non-exhaustive match`);
})())((parseAddSub)(toks));

const parseAddSub = (toks: Token[]) => (([e, rest]) => ((parseAddSubTail)(e))(rest))((parseMulDiv)(toks));

const parseAddSubTail = (lhs: Expr) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Plus`) { const rest = _ll_s.slice(1); return (([r, rest2]) => ((parseAddSubTail)(EBinOp(`+`, lhs, r)))(rest2))((parseMulDiv)(rest)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Minus`) { const rest = _ll_s.slice(1); return (([r, rest2]) => ((parseAddSubTail)(EBinOp(`-`, lhs, r)))(rest2))((parseMulDiv)(rest)); }
  return [lhs, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseMulDiv = (toks: Token[]) => (([e, rest]) => ((parseMulDivTail)(e))(rest))((parseApp)(toks));

const parseMulDivTail = (lhs: Expr) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Star`) { const rest = _ll_s.slice(1); return (([r, rest2]) => ((parseMulDivTail)(EBinOp(`*`, lhs, r)))(rest2))((parseApp)(rest)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Slash`) { const rest = _ll_s.slice(1); return (([r, rest2]) => ((parseMulDivTail)(EBinOp(`/`, lhs, r)))(rest2))((parseApp)(rest)); }
  return [lhs, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseApp = (toks: Token[]) => (([e, rest]) => ((parseAppTail)(e))(rest))((parseAtom)(toks));

const parseAppTail = (lhs: Expr) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1) { const t = _ll_s[0]; return ((isAtomStart)(t) ? (([arg, rest]) => ((parseAppTail)(EApp(lhs, arg)))(rest))((parseAtom)(toks)) : [lhs, toks] as const); }
  return [lhs, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseListLit = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `RBrack`) { const rest = _ll_s.slice(1); return [ENil, rest] as const; }
  return (([e, rest]) => (() => {
  const _ll_s = rest;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `RBrack`) { const rest2 = _ll_s.slice(1); return [ECons(e, ENil), rest2] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Comma`) { const rest2 = _ll_s.slice(1); return (([tail, rest3]) => [ECons(e, tail), rest3] as const)((parseListLit)(rest2)); }
  return (([tail, rest2]) => [ECons(e, tail), rest2] as const)((parseListLit)(rest));
  throw new Error(`Non-exhaustive match`);
})())((parseListElem)(toks));
  throw new Error(`Non-exhaustive match`);
})();

const parseListElem = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { return (parseApp)(toks); }
  return (parseAtom)(toks);
  throw new Error(`Non-exhaustive match`);
})();

const parseAtomParenTail = (e: Expr) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Comma`) { const rest = _ll_s.slice(1); return ((rest2) => (([e2, rest3]) => (() => {
  const _ll_s = rest3;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `RParen`) { const rest4 = _ll_s.slice(1); return [ETuple(e, e2), rest4] as const; }
  return [ETuple(e, e2), rest3] as const;
  throw new Error(`Non-exhaustive match`);
})())((parseExpr)(rest2)))((skipNewlines)(rest)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `RParen`) { const rest = _ll_s.slice(1); return [e, rest] as const; }
  return [e, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseAtom = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `IntLit`) { const n = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [EInt(n), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `FloatLit`) { const s = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [EFloat(s), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `StrLit`) { const s = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [EStr(s), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `CharLit`) { const c = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [EChar(c), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwTrue`) { const rest = _ll_s.slice(1); return [EBool(true), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwFalse`) { const rest = _ll_s.slice(1); return [EBool(false), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { const s = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [EVar(s), rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { const s = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return [ECon(s), rest] as const; }
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `LBrack` && _ll_s[1]?._tag === `RBrack`) { const rest = _ll_s.slice(2); return [ENil, rest] as const; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `LBrack`) { const rest = _ll_s.slice(1); return (parseListLit)(rest); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `LParen`) { const rest = _ll_s.slice(1); return (([e, rest2]) => ((parseAtomParenTail)(e))(rest2))((parseExpr)(rest)); }
  return [EInt(0), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const lastParamVar = (prms: Param[]) => (() => {
  const _ll_s = prms;
  if (_ll_s.length === 0) { return EInt(0); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `MkParam`) { const n = (_ll_s[0] as Record<string, unknown>)[`_0`]; return EVar(n); }
  if (_ll_s.length >= 1) { const rest = _ll_s.slice(1); return (lastParamVar)(rest); }
  throw new Error(`Non-exhaustive match`);
})();

const parseFnBody = (prms: Param[]) => (toks: Token[]) => ((toks2) => (() => {
  const _ll_s = toks2;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Bar`) { return (([armLists, rest]) => (([pats, bodies]) => ((scrut) => [EMatch(scrut, pats, bodies), rest] as const)((lastParamVar)(prms)))(armLists))((parseArms)(toks2)); }
  return (parseExpr)(toks2);
  throw new Error(`Non-exhaustive match`);
})())((skipNewlines)(toks));

const parseFnDecl = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { const name = (_ll_s[0] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(1); return (([prms, rest2]) => (([retTy, rest3]) => ((rest4) => (([body, rest5]) => [DFn(name, prms, retTy, body), rest5] as const)(((parseFnBody)(prms))(rest4)))((() => {
  const _ll_s = (skipNewlines)(rest3);
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Eq`) { const r = _ll_s.slice(1); return (skipNewlines)(r); }
  return (skipNewlines)(rest3);
  throw new Error(`Non-exhaustive match`);
})()))((parseReturnType)(rest2)))((parseParamGroups)(rest)); }
  return [DFn(`?`, [], None, EInt(0)), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseLetDecl = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 3 && _ll_s[0]?._tag === `KwLet` && _ll_s[1]?._tag === `Ident` && _ll_s[2]?._tag === `Eq`) { const name = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(3); return ((rest0) => (([body, rest2]) => [DLet(name, body), rest2] as const)((parseExpr)(rest0)))((skipNewlines)(rest)); }
  return [DLet(`?`, EInt(0)), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseImportPath = (acc: string[]) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `Dot` && _ll_s[1]?._tag === `TypeId`) { const seg = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(2); return ((parseImportPath)(((listAppend)(acc))([seg])))(rest); }
  return [acc, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseImportDecl = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `KwImport` && _ll_s[1]?._tag === `TypeId`) { const head = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(2); return (([segs, rest2]) => [DImport(segs), rest2] as const)(((parseImportPath)([head]))(rest)); }
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `KwImport` && _ll_s[1]?._tag === `StrLit`) { const url = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(2); return [DImportUrl(url), rest] as const; }
  return [DImport([]), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseExternalDecl = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `KwExternal` && _ll_s[1]?._tag === `Ident`) { const name = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(2); return (([prms, rest2]) => (([retTy, rest3]) => ((retFinal) => [DExternal(name, prms, retFinal), rest3] as const)((() => {
  const _ll_s = retTy;
  if (_ll_s?._tag === `Some`) { const ty = (_ll_s as Record<string, unknown>)[`_0`]; return ty; }
  if (_ll_s?._tag === `None`) { return TyName(`?`); }
  throw new Error(`Non-exhaustive match`);
})()))((parseReturnType)(rest2)))((parseParamGroups)(rest)); }
  return [DExternal(`?`, [], TyName(`?`)), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseOpaqueDecl = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `KwOpaque` && _ll_s[1]?._tag === `TypeId`) { const name = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(2); return [DOpaque(name), rest] as const; }
  return [DOpaque(`?`), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseOneDecl = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { return (parseTypeDecl)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwLet`) { return (parseLetDecl)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { return (parseFnDecl)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwImport`) { return (parseImportDecl)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwExternal`) { return (parseExternalDecl)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwOpaque`) { return (parseOpaqueDecl)(toks); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwExport`) { const rest = _ll_s.slice(1); return (([inner, rest2]) => [DExport(inner), rest2] as const)((parseOneDecl)(rest)); }
  return [DLet(`?`, EInt(0)), toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseDecls = (toks: Token[]) => ((toks2) => (() => {
  const _ll_s = toks2;
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Eof`) { return []; }
  if (_ll_s.length === 0) { return []; }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `TypeId`) { return (([d, rest]) => [d, ...(parseDecls)(rest)])((parseTypeDecl)(toks2)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwLet`) { return (([d, rest]) => [d, ...(parseDecls)(rest)])((parseLetDecl)(toks2)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `Ident`) { return (([d, rest]) => [d, ...(parseDecls)(rest)])((parseFnDecl)(toks2)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwImport`) { return (([d, rest]) => [d, ...(parseDecls)(rest)])((parseImportDecl)(toks2)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwExternal`) { return (([d, rest]) => [d, ...(parseDecls)(rest)])((parseExternalDecl)(toks2)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwOpaque`) { return (([d, rest]) => [d, ...(parseDecls)(rest)])((parseOpaqueDecl)(toks2)); }
  if (_ll_s.length >= 1 && _ll_s[0]?._tag === `KwExport`) { const rest = _ll_s.slice(1); return (([inner, rest2]) => [DExport(inner), ...(parseDecls)(rest2)])((parseOneDecl)(rest)); }
  return [];
  throw new Error(`Non-exhaustive match`);
})())((skipNewlines)(toks));

const parseModulePath = (acc: string[]) => (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `Dot` && _ll_s[1]?._tag === `TypeId`) { const seg = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(2); return ((parseModulePath)(((listAppend)(acc))([seg])))(rest); }
  return [acc, toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseModuleHeader = (toks: Token[]) => (() => {
  const _ll_s = toks;
  if (_ll_s.length >= 2 && _ll_s[0]?._tag === `KwModule` && _ll_s[1]?._tag === `TypeId`) { const head = (_ll_s[1] as Record<string, unknown>)[`_0`]; const rest = _ll_s.slice(2); return (([segs, rest2]) => [segs, rest2] as const)(((parseModulePath)([head]))(rest)); }
  return [[], toks] as const;
  throw new Error(`Non-exhaustive match`);
})();

const parseModule = (toks: Token[]) => ((toks2) => (([path, rest]) => ((decls) => MkModule(path, decls))((parseDecls)((skipNewlines)(rest))))((parseModuleHeader)(toks2)))((skipNewlines)(toks));

const boolToStr = (b: boolean) => (b ? `true` : `false`);

const showExpr = (e: Expr) => (() => {
  const _ll_s = e;
  if (_ll_s?._tag === `EInt`) { const n = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`EInt `))((intToStr)(n)); }
  if (_ll_s?._tag === `EStr`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`EStr `))(s); }
  if (_ll_s?._tag === `EBool`) { const b = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`EBool `))((boolToStr)(b)); }
  if (_ll_s?._tag === `EChar`) { const c = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`EChar `))((strFromChars)([c])); }
  if (_ll_s?._tag === `EFloat`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`EFloat `))(s); }
  if (_ll_s?._tag === `EVar`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`EVar `))(s); }
  if (_ll_s?._tag === `ECon`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`ECon `))(s); }
  if (_ll_s?._tag === `ENil`) { return `ENil`; }
  if (_ll_s?._tag === `ECons`) { const h = (_ll_s as Record<string, unknown>)[`_0`]; const t = (_ll_s as Record<string, unknown>)[`_1`]; return ((strConcat)(((strConcat)(`ECons(`))((showExpr)(h))))(((strConcat)(` `))(((strConcat)((showExpr)(t)))(`)`))); }
  if (_ll_s?._tag === `EApp`) { const f = (_ll_s as Record<string, unknown>)[`_0`]; const x = (_ll_s as Record<string, unknown>)[`_1`]; return ((strConcat)(((strConcat)(`EApp(`))((showExpr)(f))))(((strConcat)(` `))(((strConcat)((showExpr)(x)))(`)`))); }
  if (_ll_s?._tag === `EIf`) { const c = (_ll_s as Record<string, unknown>)[`_0`]; const a = (_ll_s as Record<string, unknown>)[`_1`]; const b = (_ll_s as Record<string, unknown>)[`_2`]; return ((strConcat)(`EIf(`))(((strConcat)((showExpr)(c)))(((strConcat)(` `))(((strConcat)((showExpr)(a)))(((strConcat)(` `))(((strConcat)((showExpr)(b)))(`)`)))))); }
  if (_ll_s?._tag === `EBinOp`) { const op = (_ll_s as Record<string, unknown>)[`_0`]; const l = (_ll_s as Record<string, unknown>)[`_1`]; const r = (_ll_s as Record<string, unknown>)[`_2`]; return ((strConcat)(`EBinOp(`))(((strConcat)(op))(((strConcat)(` `))(((strConcat)((showExpr)(l)))(((strConcat)(` `))(((strConcat)((showExpr)(r)))(`)`)))))); }
  if (_ll_s?._tag === `ETuple`) { const a = (_ll_s as Record<string, unknown>)[`_0`]; const b = (_ll_s as Record<string, unknown>)[`_1`]; return ((strConcat)(`ETuple(`))(((strConcat)((showExpr)(a)))(((strConcat)(` `))(((strConcat)((showExpr)(b)))(`)`)))); }
  if (_ll_s?._tag === `ELet`) { const n = (_ll_s as Record<string, unknown>)[`_0`]; const e1 = (_ll_s as Record<string, unknown>)[`_1`]; const e2 = (_ll_s as Record<string, unknown>)[`_2`]; return ((strConcat)(`ELet `))(((strConcat)(n))(((strConcat)(`=(`))(((strConcat)((showExpr)(e1)))(((strConcat)(`) in (`))(((strConcat)((showExpr)(e2)))(`)`)))))); }
  if (_ll_s?._tag === `ELam`) { const n = (_ll_s as Record<string, unknown>)[`_0`]; const b = (_ll_s as Record<string, unknown>)[`_1`]; return ((strConcat)(`ELam `))(((strConcat)(n))(((strConcat)(`.`))((showExpr)(b)))); }
  if (_ll_s?._tag === `EMatch`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; const pats = (_ll_s as Record<string, unknown>)[`_1`]; const bodies = (_ll_s as Record<string, unknown>)[`_2`]; return ((strConcat)(`EMatch(`))(((strConcat)((showExpr)(s)))(`...)`)); }
  if (_ll_s?._tag === `EList`) { const es = (_ll_s as Record<string, unknown>)[`_0`]; return `EList(...)`; }
  throw new Error(`Non-exhaustive match`);
})();

const showPattern = (p: Pattern) => (() => {
  const _ll_s = p;
  if (_ll_s?._tag === `PVar`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`PVar `))(s); }
  if (_ll_s?._tag === `PWild`) { return `PWild`; }
  if (_ll_s?._tag === `PCon`) { const name = (_ll_s as Record<string, unknown>)[`_0`]; const args = (_ll_s as Record<string, unknown>)[`_1`]; return ((strConcat)(`PCon `))(name); }
  if (_ll_s?._tag === `PLitInt`) { const n = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`PLitInt `))((intToStr)(n)); }
  if (_ll_s?._tag === `PLitStr`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`PLitStr `))(s); }
  if (_ll_s?._tag === `PCons`) { const h = (_ll_s as Record<string, unknown>)[`_0`]; const t = (_ll_s as Record<string, unknown>)[`_1`]; return ((strConcat)(`PCons(`))(((strConcat)((showPattern)(h)))(((strConcat)(` `))(((strConcat)((showPattern)(t)))(`)`)))); }
  if (_ll_s?._tag === `PNil`) { return `PNil`; }
  throw new Error(`Non-exhaustive match`);
})();

const showMaybeTy = (m: TypeExpr | null) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `Some`) {  return `Some`; }
  if (_ll_s?._tag === `None`) { return `None`; }
  throw new Error(`Non-exhaustive match`);
})();

const joinDot = (segs: string[]) => (((listFold)((acc: string) => (s: string) => (((strLen)(acc) === 0) ? s : ((strConcat)(((strConcat)(acc))(`.`)))(s))))(``))(segs);

const showDecl = (d: Decl) => (() => {
  const _ll_s = d;
  if (_ll_s?._tag === `DFn`) { const name = (_ll_s as Record<string, unknown>)[`_0`]; const prms = (_ll_s as Record<string, unknown>)[`_1`]; const retTy = (_ll_s as Record<string, unknown>)[`_2`]; const body = (_ll_s as Record<string, unknown>)[`_3`]; return ((strConcat)(`DFn `))(((strConcat)(name))(((strConcat)(` body=(`))(((strConcat)((showExpr)(body)))(`)`)))); }
  if (_ll_s?._tag === `DType`) { const name = (_ll_s as Record<string, unknown>)[`_0`]; const prms = (_ll_s as Record<string, unknown>)[`_1`]; const ctors = (_ll_s as Record<string, unknown>)[`_2`]; return ((strConcat)(`DType `))(name); }
  if (_ll_s?._tag === `DImport`) { const segs = (_ll_s as Record<string, unknown>)[`_0`]; return ((path) => ((strConcat)(`DImport `))(path))((joinDot)(segs)); }
  if (_ll_s?._tag === `DImportUrl`) { const url = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`DImportUrl `))(url); }
  if (_ll_s?._tag === `DExport`) { const inner = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`DExport(`))(((strConcat)((showDecl)(inner)))(`)`)); }
  if (_ll_s?._tag === `DLet`) { const name = (_ll_s as Record<string, unknown>)[`_0`]; const body = (_ll_s as Record<string, unknown>)[`_1`]; return ((strConcat)(`DLet `))(((strConcat)(name))(((strConcat)(`=(`))(((strConcat)((showExpr)(body)))(`)`)))); }
  if (_ll_s?._tag === `DExternal`) { const name = (_ll_s as Record<string, unknown>)[`_0`]; const _prms = (_ll_s as Record<string, unknown>)[`_1`]; const _retTy = (_ll_s as Record<string, unknown>)[`_2`]; return ((strConcat)(`DExternal `))(name); }
  if (_ll_s?._tag === `DOpaque`) { const name = (_ll_s as Record<string, unknown>)[`_0`]; return ((strConcat)(`DOpaque `))(name); }
  throw new Error(`Non-exhaustive match`);
})();

const parserCheckExpr = (label: string) => (toks: Token[]) => (expected: string) => (([e, _rest]) => ((got) => ((got === expected) ? (printfn)(((strConcat)(`OK `))(label)) : ((p1) => ((p2) => ((p3) => ((p4) => ((p5) => (printfn)(p5))(((strConcat)(p4))(got)))(((strConcat)(p3))(`\n  got:      `)))(((strConcat)(p2))(expected)))(((strConcat)(p1))(`\n  expected: `)))(((strConcat)(`FAIL `))(label))))((showExpr)(e)))((parseExpr)((skipNewlines)(toks)));

const parserCheckDecl = (label: string) => (toks: Token[]) => (expected: string) => (([d, _rest]) => ((got) => ((got === expected) ? (printfn)(((strConcat)(`OK `))(label)) : ((p1) => ((p2) => ((p3) => ((p4) => ((p5) => (printfn)(p5))(((strConcat)(p4))(got)))(((strConcat)(p3))(`\n  got:      `)))(((strConcat)(p2))(expected)))(((strConcat)(p1))(`\n  expected: `)))(((strConcat)(`FAIL `))(label))))((showDecl)(d)))((parseOneDecl)((skipNewlines)(toks)));

const parserCheckModule = (label: string) => (toks: Token[]) => (expectedDeclCount: number) => ((m) => (() => {
  const _ll_s = m;
  if (_ll_s?._tag === `MkModule`) { const path = (_ll_s as Record<string, unknown>)[`_0`]; const decls = (_ll_s as Record<string, unknown>)[`_1`]; return ((n) => ((n === expectedDeclCount) ? (printfn)(((strConcat)(`OK `))(label)) : ((p1) => ((p2) => ((p3) => ((p4) => ((p5) => (printfn)(p5))(((strConcat)(p4))((intToStr)(n))))(((strConcat)(p3))(` decls, got `)))(((strConcat)(p2))((intToStr)(expectedDeclCount))))(((strConcat)(p1))(` expected `)))(((strConcat)(`FAIL `))(label))))((listLen)(decls)); }
  throw new Error(`Non-exhaustive match`);
})())((parseModule)(toks));

const __ll_main_Std_Parser = () => {};

type InferResult<A> = { _tag: `InferOk`; _0: unknown } | { _tag: `InferErr`; _0: string };
const InferOk = <A>(_0: unknown): InferResult<A> => ({ _tag: `InferOk` as const, _0 });
const InferErr = <A>(_0: string): InferResult<A> => ({ _tag: `InferErr` as const, _0 });

type Scheme = { _tag: `MkScheme`; _0: string[]; _1: TypeExpr };
const MkScheme = (_0: string[], _1: TypeExpr): Scheme => ({ _tag: `MkScheme` as const, _0, _1 });

type Fresh = { _tag: `MkFresh`; _0: number };
const MkFresh = (_0: number): Fresh => ({ _tag: `MkFresh` as const, _0 });

const isFlex = (name: string) => (((strLen)(name) > 0) ? ((((strSlice)(name))(0))(1) === `\$`) : false);

const freshVarName = (n: number) => ((strConcat)(`\$`))((intToStr)(n));

const schemeMono = (t: TypeExpr) => MkScheme([], t);

const schemeVars = (s: Scheme) => (() => {
  const _ll_s = s;
  if (_ll_s?._tag === `MkScheme`) { const vs = (_ll_s as Record<string, unknown>)[`_0`]; return vs; }
  throw new Error(`Non-exhaustive match`);
})();

const schemeBody = (s: Scheme) => (() => {
  const _ll_s = s;
  if (_ll_s?._tag === `MkScheme`) { const body = (_ll_s as Record<string, unknown>)[`_1`]; return body; }
  throw new Error(`Non-exhaustive match`);
})();

const substEmpty = (() => Leaf)();

const substInsert = (v: string) => (t: TypeExpr) => (s: RBMap<string, TypeExpr>) => ((((mapInsert)(strCmp))(v))(t))(s);

const substLookup = (v: string) => (s: RBMap<string, TypeExpr>) => (((mapLookup)(strCmp))(v))(s);

const substRemove = (v: string) => (s: RBMap<string, TypeExpr>) => (((mapFold)((acc: RBMap<string, TypeExpr>) => (nk: string) => (nv: TypeExpr) => ((((strCmp)(v))(nk) === 0) ? acc : ((((mapInsert)(strCmp))(nk))(nv))(acc))))(Leaf))(s);

const applyType = (s: RBMap<string, TypeExpr>) => (t: TypeExpr) => (() => {
  const _ll_s = t;
  if (_ll_s?._tag === `TyName`) { const v = (_ll_s as Record<string, unknown>)[`_0`]; return ((isFlex)(v) ? (() => {
  const _ll_s = ((substLookup)(v))(s);
  if (_ll_s?._tag === `Some`) { const t2 = (_ll_s as Record<string, unknown>)[`_0`]; return ((applyType)(s))(t2); }
  if (_ll_s?._tag === `None`) { return t; }
  throw new Error(`Non-exhaustive match`);
})() : t); }
  if (_ll_s?._tag === `TyApp`) { const a = (_ll_s as Record<string, unknown>)[`_0`]; const b = (_ll_s as Record<string, unknown>)[`_1`]; return TyApp(((applyType)(s))(a), ((applyType)(s))(b)); }
  if (_ll_s?._tag === `TyFn`) { const a = (_ll_s as Record<string, unknown>)[`_0`]; const b = (_ll_s as Record<string, unknown>)[`_1`]; return TyFn(((applyType)(s))(a), ((applyType)(s))(b)); }
  throw new Error(`Non-exhaustive match`);
})();

const applyScheme = (s: RBMap<string, TypeExpr>) => (sch: Scheme) => (() => {
  const _ll_s = sch;
  if (_ll_s?._tag === `MkScheme`) { const vs = (_ll_s as Record<string, unknown>)[`_0`]; const body = (_ll_s as Record<string, unknown>)[`_1`]; return ((s2) => MkScheme(vs, ((applyType)(s2))(body)))((((listFold)((acc: RBMap<string, TypeExpr>) => (v: string) => ((substRemove)(v))(acc)))(s))(vs)); }
  throw new Error(`Non-exhaustive match`);
})();

const applyEnv = (s: RBMap<string, TypeExpr>) => (env: RBMap<string, Scheme>) => (((mapFold)((acc: RBMap<string, Scheme>) => (k: string) => (sch: Scheme) => ((((mapInsert)(strCmp))(k))(((applyScheme)(s))(sch)))(acc)))(Leaf))(env);

const substCompose = (s1: RBMap<string, TypeExpr>) => (s2: RBMap<string, TypeExpr>) => ((s2Applied) => (((mapFold)((acc: RBMap<string, TypeExpr>) => (k: string) => (v: TypeExpr) => (() => {
  const _ll_s = ((substLookup)(k))(acc);
  if (_ll_s?._tag === `None`) { return ((((mapInsert)(strCmp))(k))(v))(acc); }
  if (_ll_s?._tag === `Some`) {  return acc; }
  throw new Error(`Non-exhaustive match`);
})()))(s2Applied))(s1))((((mapFold)((acc: RBMap<string, TypeExpr>) => (k: string) => (t: TypeExpr) => ((((mapInsert)(strCmp))(k))(((applyType)(s1))(t)))(acc)))(Leaf))(s2));

const ftvTypeList = (t: TypeExpr) => (() => {
  const _ll_s = t;
  if (_ll_s?._tag === `TyName`) { const v = (_ll_s as Record<string, unknown>)[`_0`]; return ((isFlex)(v) ? [v] : []); }
  if (_ll_s?._tag === `TyApp`) { const a = (_ll_s as Record<string, unknown>)[`_0`]; const b = (_ll_s as Record<string, unknown>)[`_1`]; return (strNub)(((listAppend)((ftvTypeList)(a)))((ftvTypeList)(b))); }
  if (_ll_s?._tag === `TyFn`) { const a = (_ll_s as Record<string, unknown>)[`_0`]; const b = (_ll_s as Record<string, unknown>)[`_1`]; return (strNub)(((listAppend)((ftvTypeList)(a)))((ftvTypeList)(b))); }
  throw new Error(`Non-exhaustive match`);
})();

const ftvSchemeList = (sch: Scheme) => (() => {
  const _ll_s = sch;
  if (_ll_s?._tag === `MkScheme`) { const vs = (_ll_s as Record<string, unknown>)[`_0`]; const body = (_ll_s as Record<string, unknown>)[`_1`]; return ((listFilter)((v: string) => ((listAll)((q: string) => (v !== q)))(vs)))((ftvTypeList)(body)); }
  throw new Error(`Non-exhaustive match`);
})();

const ftvEnvList = (env: RBMap<string, Scheme>) => (strNub)((((mapFold)((acc: string[]) => (k: string) => (sch: Scheme) => ((listAppend)(acc))((ftvSchemeList)(sch))))([]))(env));

const strNub = (xs: string[]) => (((listFold)((acc: string[]) => (x: string) => (((listAny)((y: string) => (x === y)))(acc) ? acc : ((listAppend)(acc))([x]))))([]))(xs);

const freshInit = (() => MkFresh(0))();

const freshNext = (f: Fresh) => (() => {
  const _ll_s = f;
  if (_ll_s?._tag === `MkFresh`) { const n = (_ll_s as Record<string, unknown>)[`_0`]; return [TyName((freshVarName)(n)), MkFresh((n + 1))] as const; }
  throw new Error(`Non-exhaustive match`);
})();

const generalize = (env: RBMap<string, Scheme>) => (t: TypeExpr) => ((envFtv) => ((toQuant) => MkScheme(toQuant, t))(((listFilter)((v: string) => ((listAll)((e: string) => (v !== e)))(envFtv)))((ftvTypeList)(t))))((ftvEnvList)(env));

const instantiateWith = (f: Fresh) => (vs: string[]) => (body: TypeExpr) => (() => {
  const _ll_s = vs;
  if (_ll_s.length === 0) { return [body, f] as const; }
  if (_ll_s.length >= 1) { const v = _ll_s[0]; const rest = _ll_s.slice(1); return (([tv, f2]) => ((s) => ((body2) => (((instantiateWith)(f2))(rest))(body2))(((applyType)(s))(body)))((((substInsert)(v))(tv))(substEmpty)))((freshNext)(f)); }
  throw new Error(`Non-exhaustive match`);
})();

const instantiate = (f: Fresh) => (sch: Scheme) => (() => {
  const _ll_s = sch;
  if (_ll_s?._tag === `MkScheme`) { const vs = (_ll_s as Record<string, unknown>)[`_0`]; const body = (_ll_s as Record<string, unknown>)[`_1`]; return (((instantiateWith)(f))(vs))(body); }
  throw new Error(`Non-exhaustive match`);
})();

const unify = (t1: TypeExpr) => (t2: TypeExpr) => (() => {
  const _ll_s = t1;
  if (_ll_s?._tag === `TyName`) { const a = (_ll_s as Record<string, unknown>)[`_0`]; return (() => {
  const _ll_s = t2;
  if (_ll_s?._tag === `TyName`) { const b = (_ll_s as Record<string, unknown>)[`_0`]; return ((a === b) ? InferOk(substEmpty) : ((isFlex)(a) ? ((bindVar)(a))(t2) : ((isFlex)(b) ? ((bindVar)(b))(t1) : InferErr(((unifyErrMsg)(t1))(t2))))); }
  return ((isFlex)(a) ? ((bindVar)(a))(t2) : InferErr(((unifyErrMsg)(t1))(t2)));
  throw new Error(`Non-exhaustive match`);
})(); }
  if (_ll_s?._tag === `TyApp`) { const a1 = (_ll_s as Record<string, unknown>)[`_0`]; const b1 = (_ll_s as Record<string, unknown>)[`_1`]; return (() => {
  const _ll_s = t2;
  if (_ll_s?._tag === `TyApp`) { const a2 = (_ll_s as Record<string, unknown>)[`_0`]; const b2 = (_ll_s as Record<string, unknown>)[`_1`]; return (() => {
  const _ll_s = ((unify)(a1))(a2);
  if (_ll_s?._tag === `InferErr`) { const e = (_ll_s as Record<string, unknown>)[`_0`]; return InferErr(e); }
  if (_ll_s?._tag === `InferOk`) { const s1 = (_ll_s as Record<string, unknown>)[`_0`]; return (() => {
  const _ll_s = ((unify)(((applyType)(s1))(b1)))(((applyType)(s1))(b2));
  if (_ll_s?._tag === `InferErr`) { const e = (_ll_s as Record<string, unknown>)[`_0`]; return InferErr(e); }
  if (_ll_s?._tag === `InferOk`) { const s2 = (_ll_s as Record<string, unknown>)[`_0`]; return InferOk(((substCompose)(s2))(s1)); }
  throw new Error(`Non-exhaustive match`);
})(); }
  throw new Error(`Non-exhaustive match`);
})(); }
  if (_ll_s?._tag === `TyName`) { const v = (_ll_s as Record<string, unknown>)[`_0`]; return ((isFlex)(v) ? ((bindVar)(v))(t1) : InferErr(((unifyErrMsg)(t1))(t2))); }
  return InferErr(((unifyErrMsg)(t1))(t2));
  throw new Error(`Non-exhaustive match`);
})(); }
  if (_ll_s?._tag === `TyFn`) { const a1 = (_ll_s as Record<string, unknown>)[`_0`]; const b1 = (_ll_s as Record<string, unknown>)[`_1`]; return (() => {
  const _ll_s = t2;
  if (_ll_s?._tag === `TyFn`) { const a2 = (_ll_s as Record<string, unknown>)[`_0`]; const b2 = (_ll_s as Record<string, unknown>)[`_1`]; return (() => {
  const _ll_s = ((unify)(a1))(a2);
  if (_ll_s?._tag === `InferErr`) { const e = (_ll_s as Record<string, unknown>)[`_0`]; return InferErr(e); }
  if (_ll_s?._tag === `InferOk`) { const s1 = (_ll_s as Record<string, unknown>)[`_0`]; return (() => {
  const _ll_s = ((unify)(((applyType)(s1))(b1)))(((applyType)(s1))(b2));
  if (_ll_s?._tag === `InferErr`) { const e = (_ll_s as Record<string, unknown>)[`_0`]; return InferErr(e); }
  if (_ll_s?._tag === `InferOk`) { const s2 = (_ll_s as Record<string, unknown>)[`_0`]; return InferOk(((substCompose)(s2))(s1)); }
  throw new Error(`Non-exhaustive match`);
})(); }
  throw new Error(`Non-exhaustive match`);
})(); }
  if (_ll_s?._tag === `TyName`) { const v = (_ll_s as Record<string, unknown>)[`_0`]; return ((isFlex)(v) ? ((bindVar)(v))(t1) : InferErr(((unifyErrMsg)(t1))(t2))); }
  return InferErr(((unifyErrMsg)(t1))(t2));
  throw new Error(`Non-exhaustive match`);
})(); }
  throw new Error(`Non-exhaustive match`);
})();

const unifyErrMsg = (t1: TypeExpr) => (t2: TypeExpr) => ((strConcat)(`Cannot unify `))(((strConcat)((renderType)(t1)))(((strConcat)(` with `))((renderType)(t2))));

const bindVar = (v: string) => (t: TypeExpr) => (() => {
  const _ll_s = t;
  if (_ll_s?._tag === `TyName`) { const w = (_ll_s as Record<string, unknown>)[`_0`]; return ((v === w) ? InferOk(substEmpty) : InferOk((((substInsert)(v))(t))(substEmpty))); }
  return (((occursIn)(v))(t) ? InferErr(((strConcat)(`Infinite type: `))(((strConcat)(v))(((strConcat)(` in `))((renderType)(t))))) : InferOk((((substInsert)(v))(t))(substEmpty)));
  throw new Error(`Non-exhaustive match`);
})();

const occursIn = (v: string) => (t: TypeExpr) => ((listAny)((w: string) => (v === w)))((ftvTypeList)(t));

const renderType = (t: TypeExpr) => (() => {
  const _ll_s = t;
  if (_ll_s?._tag === `TyName`) { const n = (_ll_s as Record<string, unknown>)[`_0`]; return n; }
  if (_ll_s?._tag === `TyApp`) { const f = (_ll_s as Record<string, unknown>)[`_0`]; const a = (_ll_s as Record<string, unknown>)[`_1`]; return ((aStr) => ((strConcat)((renderType)(f)))(((strConcat)(` `))(aStr)))((() => {
  const _ll_s = a;
  if (_ll_s?._tag === `TyApp`) {  return ((strConcat)(`(`))(((strConcat)((renderType)(a)))(`)`)); }
  if (_ll_s?._tag === `TyFn`) {  return ((strConcat)(`(`))(((strConcat)((renderType)(a)))(`)`)); }
  return (renderType)(a);
  throw new Error(`Non-exhaustive match`);
})()); }
  if (_ll_s?._tag === `TyFn`) { const a = (_ll_s as Record<string, unknown>)[`_0`]; const b = (_ll_s as Record<string, unknown>)[`_1`]; return ((aStr) => ((strConcat)(aStr))(((strConcat)(` -> `))((renderType)(b))))((() => {
  const _ll_s = a;
  if (_ll_s?._tag === `TyFn`) {  return ((strConcat)(`(`))(((strConcat)((renderType)(a)))(`)`)); }
  return (renderType)(a);
  throw new Error(`Non-exhaustive match`);
})()); }
  throw new Error(`Non-exhaustive match`);
})();

const typeEnvEmpty = (() => Leaf)();

const typeEnvInsert = (name: string) => (sch: Scheme) => (env: RBMap<string, Scheme>) => ((((mapInsert)(strCmp))(name))(sch))(env);

const typeEnvLookup = (name: string) => (env: RBMap<string, Scheme>) => (((mapLookup)(strCmp))(name))(env);

const typeEnvApply = (s: RBMap<string, TypeExpr>) => (env: RBMap<string, Scheme>) => ((applyEnv)(s))(env);

const extractBound = (v: string) => (r: InferResult<RBMap<string, TypeExpr>>) => (() => {
  const _ll_s = r;
  if (_ll_s?._tag === `InferOk`) { const s = (_ll_s as Record<string, unknown>)[`_0`]; return (() => {
  const _ll_s = ((substLookup)(v))(s);
  if (_ll_s?._tag === `Some`) { const t = (_ll_s as Record<string, unknown>)[`_0`]; return (renderType)(t); }
  if (_ll_s?._tag === `None`) { return `none`; }
  throw new Error(`Non-exhaustive match`);
})(); }
  if (_ll_s?._tag === `InferErr`) { const e = (_ll_s as Record<string, unknown>)[`_0`]; return e; }
  throw new Error(`Non-exhaustive match`);
})();

const typesCheck = (label: string) => (got: string) => (expected: string) => ((got === expected) ? (printfn)(((strConcat)(`OK `))(label)) : (printfn)(((strConcat)(`FAIL `))(((strConcat)(label))(((strConcat)(` expected=`))(((strConcat)(expected))(((strConcat)(` got=`))(got)))))));

const boolStr = (b: boolean) => (b ? `true` : `false`);

const strJoin = (xs: string[]) => (() => {
  const _ll_s = xs;
  if (_ll_s.length === 0) { return ``; }
  if (_ll_s.length >= 1) { const x = _ll_s[0]; return x; }
  if (_ll_s.length >= 1) { const x = _ll_s[0]; const rest = _ll_s.slice(1); return ((strConcat)(x))(((strConcat)(` `))((strJoin)(rest))); }
  throw new Error(`Non-exhaustive match`);
})();

function main(): void {
  ((_) => ((_) => ((_) => ((_) => ((_) => ((_) => ((_) => ((_) => ((s0) => ((_) => ((s1) => ((_) => ((_) => ((_) => ((_) => ((_) => ((u3) => ((_) => ((u4) => ((_) => ((sch1) => ((_) => ((sch2) => (([t5, _]) => ((_) => ((_) => ((_) => (printfn)(`Done`))((((typesCheck)(`20 occursIn false`))((boolStr)(((occursIn)(`\$0`))(TyApp(TyName(`List`), TyName(`\$1`))))))(`false`)))((((typesCheck)(`19 occursIn true`))((boolStr)(((occursIn)(`\$0`))(TyApp(TyName(`List`), TyName(`\$0`))))))(`true`)))((((typesCheck)(`18 instantiate`))((renderType)(t5)))(`\$1 -> \$1`)))(((instantiate)(MkFresh(1)))(sch2)))(MkScheme([`\$0`], TyFn(TyName(`\$0`), TyName(`\$0`)))))((((typesCheck)(`17 generalize`))((strJoin)((schemeVars)(sch1))))(`\$0`)))(((generalize)(Leaf))(TyFn(TyName(`\$0`), TyName(`\$0`)))))((((typesCheck)(`16 unify TyFn`))(((extractBound)(`\$0`))(u4)))(`Int`)))(((unify)(TyFn(TyName(`\$0`), TyName(`\$1`))))(TyFn(TyName(`Int`), TyName(`Str`)))))((((typesCheck)(`15 unify flex=Int`))(((extractBound)(`\$0`))(u3)))(`Int`)))(((unify)(TyName(`\$0`)))(TyName(`Int`))))((((typesCheck)(`14 unify mismatch`))((() => {
  const _ll_s = ((unify)(TyName(`Int`)))(TyName(`Str`));
  if (_ll_s?._tag === `InferOk`) {  return `ok`; }
  if (_ll_s?._tag === `InferErr`) {  return `err`; }
  throw new Error(`Non-exhaustive match`);
})()))(`err`)))((((typesCheck)(`13 unify same`))((() => {
  const _ll_s = ((unify)(TyName(`Int`)))(TyName(`Int`));
  if (_ll_s?._tag === `InferOk`) {  return `ok`; }
  if (_ll_s?._tag === `InferErr`) {  return `err`; }
  throw new Error(`Non-exhaustive match`);
})()))(`ok`)))((((typesCheck)(`12 applyType TyFn`))((renderType)(((applyType)(s1))(TyFn(TyName(`\$0`), TyName(`Int`))))))(`Str -> Int`)))((((typesCheck)(`11 applyType rigid`))((renderType)(((applyType)(s1))(TyName(`a`)))))(`a`)))((((typesCheck)(`10 applyType flex->Str`))((renderType)(((applyType)(s1))(TyName(`\$0`)))))(`Str`)))((((substInsert)(`\$0`))(TyName(`Str`)))(substEmpty)))((((typesCheck)(`9 applyType no-op`))((renderType)(((applyType)(s0))(TyName(`Int`)))))(`Int`)))(substEmpty))((((typesCheck)(`8 renderType App`))((renderType)(TyApp(TyName(`Maybe`), TyName(`Int`)))))(`Maybe Int`)))((((typesCheck)(`7 renderType Fn`))((renderType)(TyFn(TyName(`Int`), TyName(`Str`)))))(`Int -> Str`)))((((typesCheck)(`6 renderType Name`))((renderType)(TyName(`Int`))))(`Int`)))((((typesCheck)(`5 freshVarName 42`))((freshVarName)(42)))(`\$42`)))((((typesCheck)(`4 freshVarName 0`))((freshVarName)(0)))(`\$0`)))((((typesCheck)(`3 isFlex a=false`))((boolStr)((isFlex)(`a`))))(`false`)))((((typesCheck)(`2 isFlex Int=false`))((boolStr)((isFlex)(`Int`))))(`false`)))((((typesCheck)(`1 isFlex \$0=true`))((boolStr)((isFlex)(`\$0`))))(`true`));
}


main();