module LLLang.Tests.CodegenLLVMTests

open Xunit
open LLLang.Compiler
open LLLang.Platform
open LLLang.Elaborator

let private llSrc (src: string) : string =
    match compileToLLVM src with
    | Ok ll -> ll
    | Error es -> failwith $"LLVM codegen failed: {es}"

[<Fact>]
let ``LLVM: compileToLLVM emits module header and define`` () =
    let src = "module M\nid(x Int) Int = x"
    let ll = llSrc src
    Assert.Contains("; Generated by lllc (ll-lang LLVM backend)", ll)
    Assert.Contains("define i64 @id", ll)

[<Fact>]
let ``LLVM: compileTarget LLVM produces same as compileToLLVM`` () =
    let src = "module M\nmain() Int = 1"
    let a = compileToLLVM src
    let b = compileTarget LLVM src
    Assert.Equal(a, b)

[<Fact>]
let ``LLVM: compileTarget LLVM does not emit F# keywords`` () =
    let src = "module M\nlet x = 1"
    match compileTarget LLVM src with
    | Ok ll ->
        Assert.DoesNotContain("\nlet ", ll)
        Assert.Contains("@x = global", ll)
    | Error es -> failwith $"unexpected error: {es}"

[<Fact>]
let ``LLVM: arithmetic function emits add instruction`` () =
    let src = "module M\nadd(x Int)(y Int) Int = x + y"
    let ll = llSrc src
    Assert.Contains("define i64 @add(i64 %arg0, i64 %arg1)", ll)
    Assert.Contains("add i64 %arg0, %arg1", ll)

[<Fact>]
let ``LLVM: main emits call to user function when expression is callable`` () =
    let src = "module M\nadd(x Int)(y Int) Int = x + y\nmain() Int = add 1 2"
    let ll = llSrc src
    Assert.Contains("call i64 @add(i64 1, i64 2)", ll)
    Assert.Contains("trunc i64", ll)

[<Fact>]
let ``LLVM: arithmetic ops emit sub mul sdiv instructions`` () =
    let src = "module M\nsub1(x Int) Int = x - 1\nmul2(x Int) Int = x * 2\ndiv2(x Int) Int = x / 2"
    let ll = llSrc src
    Assert.Contains("sub i64 %arg0, 1", ll)
    Assert.Contains("mul i64 %arg0, 2", ll)
    Assert.Contains("sdiv i64 %arg0, 2", ll)

[<Fact>]
let ``LLVM: integer comparisons emit icmp predicates`` () =
    let src = "module M\neq(x Int)(y Int) Bool = x == y\nlt(x Int)(y Int) Bool = x < y\nge(x Int)(y Int) Bool = x >= y"
    let ll = llSrc src
    Assert.Contains("icmp eq i64 %arg0, %arg1", ll)
    Assert.Contains("icmp slt i64 %arg0, %arg1", ll)
    Assert.Contains("icmp sge i64 %arg0, %arg1", ll)

[<Fact>]
let ``LLVM: bool main uses zext i1 to i32`` () =
    let src = "module M\nmain() Bool = true"
    let ll = llSrc src
    Assert.Contains("zext i1 1 to i32", ll)

[<Fact>]
let ``LLVM: if expression lowers to branch and phi`` () =
    let src = "module M\nmain() Int = if true\n  1\nelse 2"
    let ll = llSrc src
    Assert.Contains("br i1 1, label %if_then_", ll)
    Assert.Contains("phi i64 [ 1, %if_then_", ll)

[<Fact>]
let ``LLVM: ADT match lowers via constructor tags`` () =
    let src =
        "module M\nFlag = On | Off\nscore(f Flag) Int = match f\n  | On -> 1\n  | Off -> 0\nmain() Int = score On"
    let ll = llSrc src
    Assert.Contains("define ptr @__ll_alloc", ll)
    Assert.Contains("icmp eq i64", ll)
    Assert.Contains("call ptr @__ll_alloc(i64 1", ll)

[<Fact>]
let ``LLVM: list literal and cons pattern lower through runtime nodes`` () =
    let src =
        "module M\nheadOr0(xs List[Int]) Int = match xs\n  | h :: _ -> h\n  | [] -> 0\nmain() Int = headOr0 [5 6]"
    let ll = llSrc src
    Assert.Contains("call ptr @__ll_alloc(i64 -1", ll)
    Assert.Contains("icmp eq i64 %", ll)
    Assert.Contains("phi i64", ll)

[<Fact>]
let ``LLVM: tuple literal and tuple pattern lower through runtime nodes`` () =
    let src =
        "module M\nmain() Int = match (1, 2)\n  | (a, _) -> a"
    let ll = llSrc src
    Assert.Contains("call ptr @__ll_alloc(i64 -1", ll)
    Assert.Contains("icmp eq ptr %", ll)
    Assert.Contains("phi i64", ll)

[<Fact>]
let ``LLVM: string literal pattern match lowers via strcmp`` () =
    let src =
        "module M\nisOk(s Str) Bool = match s\n  | \"ok\" -> true\n  | _ -> false\nmain() Bool = isOk \"ok\""
    let ll = llSrc src
    Assert.Contains("@.str0 = private unnamed_addr constant", ll)
    Assert.Contains("call i32 @strcmp(ptr", ll)
    Assert.Contains("icmp eq i32", ll)

[<Fact>]
let ``LLVM: string let emits global ptr to pooled literal`` () =
    let src = "module M\nlet greeting = \"hello\""
    let ll = llSrc src
    Assert.Contains("@.str0 = private unnamed_addr constant", ll)
    Assert.Contains("@greeting = global ptr getelementptr inbounds", ll)

[<Fact>]
let ``LLVM: nested constructor string pattern lowers recursively`` () =
    let src =
        "module M\nWrap = Wrap Str\nisOk(w Wrap) Bool = match w\n  | Wrap \"ok\" -> true\n  | _ -> false\nmain() Bool = isOk (Wrap \"ok\")"
    let ll = llSrc src
    Assert.Contains("inttoptr i64", ll)
    Assert.Contains("call i32 @strcmp(ptr", ll)

[<Fact>]
let ``LLVM: nested tuple pattern lowers recursively`` () =
    let src =
        "module M\nmain() Int = match (1, (2, 3))\n  | (_, (b, _)) -> b\n  | _ -> 0"
    let ll = llSrc src
    Assert.Contains("inttoptr i64", ll)
    Assert.Contains("call ptr @__ll_alloc(i64 -1", ll)

[<Fact>]
let ``LLVM: impl methods emit as prefixed top-level functions`` () =
    let src =
        "module M\ntrait Show T =\n  show(x T) Str\nBox = MkBox Int\nimpl Show Box =\n  show(x Box) Str = \"box\"\nmain() Int = 0"
    let ll = llSrc src
    Assert.Contains("define ptr @show_Box(ptr %arg0)", ll)
    Assert.DoesNotContain("define ptr @show(", ll)

[<Fact>]
let ``LLVM: external console_log emits declare and call`` () =
    let src =
        "module M\n"
        + "external console_log(msg Str) Unit\n"
        + "main() Unit = console_log \"hi\"\n"
    let ll = llSrc src
    Assert.Contains("declare void @console_log(ptr)", ll)
    Assert.Contains("call void @console_log(ptr", ll)

[<Fact>]
let ``LLVM: unknown external declaration raises E026`` () =
    let src =
        "module M\n"
        + "external host_log(msg Str) Unit\n"
        + "main() Unit = host_log \"hi\"\n"
    match compileToLLVM src with
    | Ok ll -> failwith $"unexpected success: {ll}"
    | Error es ->
        let e = es |> List.exactlyOne
        Assert.Equal(E026, e.Code)
        Assert.Contains("UnknownExternalMapping", e.Message)
        Assert.Contains("target:llvm", e.Message)
        Assert.Contains("name:host_log", e.Message)
