# Generated by lllc (ll-lang Python backend)

# --- ll-lang stdlib (Python) ---
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Union, Callable, TypeVar
import sys
import math

A = TypeVar("A")
B = TypeVar("B")
C = TypeVar("C")
D = TypeVar("D")
E = TypeVar("E")
F = TypeVar("F")
T = TypeVar("T")
U = TypeVar("U")


def _ll_abs(x: int) -> int: return abs(x)
def absf(x: float) -> float: return abs(x)
def sqrt(x: float) -> float: return math.sqrt(x)
def _ll_min(a: int) -> Callable[[int], int]: return lambda b: min(a, b)
def _ll_max(a: int) -> Callable[[int], int]: return lambda b: max(a, b)
def intToFloat(n: int) -> float: return float(n)
def floatToInt(f: float) -> int: return int(f)
def printfn(s: str) -> None: print(s)
def _ll_print(s: str) -> None: sys.stdout.write(s)
def readFile(path: str) -> str:
    with open(path, 'r', encoding='utf-8') as f: return f.read()
def writeFile(path: str) -> Callable[[str], None]:
    def _write(contents: str) -> None:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(contents)
    return _write
def _ll_exit(n: int) -> None: sys.exit(n)
def getArgs() -> list[str]: return sys.argv[1:]
def strLen(s: str) -> int: return len(s)
def strConcat(a: str) -> Callable[[str], str]: return lambda b: a + b
def strTrim(s: str) -> str: return s.strip()
def strContains(needle: str) -> Callable[[str], bool]: return lambda hay: needle in hay
def strSplit(sep: str) -> Callable[[str], list[str]]: return lambda s: s.split(sep)
def strSlice(s: str) -> Callable: return lambda start: lambda length: s[start:start+length]
def strIndexOf(needle: str) -> Callable[[str], int]: return lambda hay: hay.find(needle)
def strReverse(s: str) -> str: return s[::-1]
def strFromChars(cs: list[str]) -> str: return ''.join(cs)
def strChars(s: str) -> list[str]: return list(s)
def intToStr(n: int) -> str: return str(n)
def floatToStr(f: float) -> str: return str(f)
def strToInt(s: str) -> Optional[int]:
    try: return int(s)
    except ValueError: return None
def strToFloat(s: str) -> Optional[float]:
    try:
        n = float(s)
        return n if math.isfinite(n) else None
    except ValueError:
        return None
def listLen(xs: list[T]) -> int: return len(xs)
def listMap(f: Callable[[T], U]) -> Callable[[list[T]], list[U]]: return lambda xs: list(map(f, xs))
def listFilter(p: Callable[[T], bool]) -> Callable[[list[T]], list[T]]: return lambda xs: list(filter(p, xs))
def listFold(f: Callable[[U], Callable[[T], U]]) -> Callable[[U], Callable[[list[T]], U]]:
    def _with_seed(z: U) -> Callable[[list[T]], U]:
        def _fold(xs: list[T]) -> U:
            acc = z
            for x in xs:
                acc = f(acc)(x)
            return acc
        return _fold
    return _with_seed
def listHead(xs: list[T]) -> Optional[T]: return xs[0] if xs else None
def listTail(xs: list[T]) -> Optional[list[T]]: return xs[1:] if xs else None
def listReverse(xs: list[T]) -> list[T]: return list(reversed(xs))
def listAppend(xs: list[T]) -> Callable[[list[T]], list[T]]: return lambda ys: xs + ys
def listIsEmpty(xs: list[T]) -> bool: return len(xs) == 0
def listContains(xs: list[T]) -> Callable[[T], bool]: return lambda x: x in xs
def listRange(lo: int) -> Callable[[int], list[int]]: return lambda hi: list(range(lo, hi))
def listConcat(xss: list[list[T]]) -> list[T]: return [x for xs in xss for x in xs]
def listAt(xs: list[T]) -> Callable[[int], Optional[T]]: return lambda i: xs[i] if 0 <= i < len(xs) else None
def charToInt(c: str) -> int: return ord(c)
def intToChar(n: int) -> str: return chr(n)
def charIsDigit(c: str) -> bool: return c.isdigit()
def charIsAlpha(c: str) -> bool: return c.isalpha()
def charIsSpace(c: str) -> bool: return c.isspace()
def maybeMap(f: Callable[[T], U]) -> Callable[[Optional[T]], Optional[U]]: return lambda m: f(m) if m is not None else None
def maybeBind(m: Optional[T]) -> Callable[[Callable[[T], Optional[U]]], Optional[U]]: return lambda f: f(m) if m is not None else None
def maybeWithDefault(d: T) -> Callable[[Optional[T]], T]: return lambda m: m if m is not None else d
def maybeDefault(d: T) -> Callable[[Optional[T]], T]: return maybeWithDefault(d)
def maybeIsNone(m: Optional[T]) -> bool: return m is None
def resultMap(f: Callable[[T], U]) -> Callable[[tuple[bool, T | E]], tuple[bool, U | E]]: return lambda r: (True, f(r[1])) if r[0] else (False, r[1])
def resultBind(r: tuple[bool, T | E]) -> Callable[[Callable[[T], tuple[bool, U | E]]], tuple[bool, U | E]]: return lambda f: f(r[1]) if r[0] else (False, r[1])
def resultMapErr(f: Callable[[E], F]) -> Callable[[tuple[bool, T | E]], tuple[bool, T | F]]:
    return lambda r: (True, r[1]) if r[0] else (False, f(r[1]))
def resultIsOk(r: tuple[bool, T | E]) -> bool: return r[0]
# --- end prelude ---


def sumFloats(xs: list[float]) -> float:
    return (0.0 if len(xs) == 0 else (lambda x, rest: (x + (sumFloats)(rest)))(xs[0], xs[1:]))

def dot(a: list[float]):
    def _f_b(b: list[float]):
        return (0.0 if len(a) == 0 else (lambda x, xs: (0.0 if len(b) == 0 else (lambda y, ys: ((x * y) + ((dot)(xs))(ys)))(b[0], b[1:])))(a[0], a[1:]))
    return _f_b

def reluVec(xs: list[float]) -> list[float]:
    return ([] if len(xs) == 0 else (lambda x, rest: (lambda head: [head] + (reluVec)(rest))((x if (x > 0.0) else 0.0)))(xs[0], xs[1:]))

def linearUnit(weights: list[float]):
    def _f_bias(bias: float):
        def _f_x(x: list[float]):
            return (((dot)(weights))(x) + bias)
        return _f_x
    return _f_bias

def layerForward(weights: list[list[float]]):
    def _f_biases(biases: list[float]):
        def _f_x(x: list[float]):
            return ([] if len(weights) == 0 else (lambda w, ws: ([] if len(biases) == 0 else (lambda b, bs: [(((linearUnit)(w))(b))(x)] + (((layerForward)(ws))(bs))(x))(biases[0], biases[1:])))(weights[0], weights[1:]))
        return _f_x
    return _f_biases

w1 = [[0.1, 0.2, -0.3], [-0.4, 0.5, 0.6], [0.7, -0.8, 0.9], [0.15, 0.25, 0.35], [-0.45, -0.55, 0.65]]

b1 = [0.01, 0.02, -0.03, 0.04, -0.05]

w2 = [[0.1, -0.2, 0.3, -0.4, 0.5]]

b2 = [0.1]

def forward(x: list[float]) -> list[float]:
    return (lambda h: (lambda hRelu: (((layerForward)(w2))(b2))(hRelu))((reluVec)(h)))((((layerForward)(w1))(b1))(x))

def mseLoss(pred: list[float]):
    def _f_target(target: list[float]):
        return (0.0 if len(pred) == 0 else (lambda p, ps: (0.0 if len(target) == 0 else (lambda t, ts: (lambda d: ((d * d) + ((mseLoss)(ps))(ts)))((p - t)))(target[0], target[1:])))(pred[0], pred[1:]))
    return _f_target

def showVec(xs: list[float]) -> str:
    return ("" if len(xs) == 0 else (lambda x, rest: ((floatToStr)(x) if len(rest) == 0 else ((strConcat)(((strConcat)((floatToStr)(x)))(", ")))((showVec)(rest))))(xs[0], xs[1:]))

def main() -> None:
    (lambda x: (lambda _tmp: (lambda s: (lambda _tmp: (lambda h: (lambda _tmp: (lambda hRelu: (lambda _tmp: (lambda y: (lambda _tmp: (lambda target: (lambda loss: (lambda _tmp: (lambda _tmp: 0)((printfn)(((strConcat)("loss  =  "))((floatToStr)(loss)))))((printfn)(((strConcat)("target:  ["))(((strConcat)((showVec)(target)))("]")))))(((mseLoss)(y))(target)))([0.5]))((printfn)(((strConcat)("output:  ["))(((strConcat)((showVec)(y)))("]")))))((forward)(x)))((printfn)(((strConcat)("hidden (relu):     ["))(((strConcat)((showVec)(hRelu)))("]")))))((reluVec)(h)))((printfn)(((strConcat)("hidden (pre-relu): ["))(((strConcat)((showVec)(h)))("]")))))((((layerForward)(w1))(b1))(x)))((printfn)(((strConcat)("sum = "))((floatToStr)(s)))))((sumFloats)(x)))((printfn)(((strConcat)("input:   ["))(((strConcat)((showVec)(x)))("]")))))([1.0, 2.0, 3.0])


if __name__ == '__main__':
    main()