"""PyTorch companion for the ll-lang MLP demo (issue #153).

Imports the ll-lang-generated forward pass from ``Main.py`` (compiled from
``Main.lll``) and cross-checks it against an equivalent ``torch.nn`` model
built from the same hardcoded weights. Then runs one ``loss.backward()``
step and prints the gradient of the first-layer weight.

Usage::

    # 1. Compile the ll-lang source to Python
    dotnet /path/to/lllc.dll build --target py src/Main.lll

    # 2. Run this script (will also execute Main.main() once via import? No —
    #    Main.py's __main__ guard prevents that; we call forward() directly)
    python src/train.py
"""

from __future__ import annotations

import os
import sys

# PyTorch on macOS occasionally ships its own libomp alongside a system one.
# This flag keeps the demo runnable without fiddling with the environment.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")

import torch
import torch.nn as nn

# Import the ll-lang-generated module sitting next to us.
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import Main as lll  # noqa: E402  — generated by lllc


def _ll_forward(x: list[float]) -> list[float]:
    """Call the ll-lang-generated forward pass on a plain Python list."""
    return lll.forward(x)


def _torch_model() -> nn.Sequential:
    """Build a torch.nn model with the exact weights embedded in Main.lll."""
    layer1 = nn.Linear(3, 5)
    layer2 = nn.Linear(5, 1)
    with torch.no_grad():
        layer1.weight.copy_(torch.tensor(lll.w1))
        layer1.bias.copy_(torch.tensor(lll.b1))
        layer2.weight.copy_(torch.tensor(lll.w2))
        layer2.bias.copy_(torch.tensor(lll.b2))
    return nn.Sequential(layer1, nn.ReLU(), layer2)


def _fmt(xs) -> str:
    if torch.is_tensor(xs):
        xs = xs.detach().tolist()
    return "[" + ", ".join(f"{v:+.6f}" for v in xs) + "]"


def main() -> None:
    x = [1.0, 2.0, 3.0]
    target = [0.5]

    print("── ll-lang (compiled from Main.lll) ─────────────────────────")
    lll_out = _ll_forward(x)
    lll_loss = lll.mseLoss(lll_out)(target)
    print(f"  output : {_fmt(lll_out)}")
    print(f"  loss   : {lll_loss:+.6f}")

    print()
    print("── PyTorch (torch.nn, same weights) ─────────────────────────")
    model = _torch_model()
    xt = torch.tensor(x, requires_grad=False)
    tt = torch.tensor(target)
    yt = model(xt)
    # Match the ll-lang loss: sum of squared residuals (not mean).
    loss = ((yt - tt) ** 2).sum()
    print(f"  output : {_fmt(yt)}")
    print(f"  loss   : {loss.item():+.6f}")

    # Equivalence check: ll-lang and torch should agree to ~1e-6.
    diff = abs(lll_loss - loss.item())
    print(f"  |Δloss|: {diff:.2e}   (ll-lang vs torch)")
    assert diff < 1e-5, "ll-lang and torch forward passes diverged"

    print()
    print("── Backward pass (PyTorch autograd) ─────────────────────────")
    loss.backward()
    # First-layer weight gradient (shape 5×3).
    w1_grad = model[0].weight.grad
    assert w1_grad is not None
    print("  grad(layer1.weight):")
    for row in w1_grad.tolist():
        print(f"    {_fmt(row)}")
    print(f"  grad(layer1.bias) : {_fmt(model[0].bias.grad)}")


if __name__ == "__main__":
    main()
