#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALLER="$ROOT_DIR/tools/bootstrap-self.sh"
LLLC="$ROOT_DIR/tools/lllc-bootstrap.sh"

fail() {
  echo "check-selfhost-e2e: $*" >&2
  exit 1
}

[[ -x "$INSTALLER" ]] || fail "missing installer: $INSTALLER"
[[ -x "$LLLC" ]] || fail "missing launcher: $LLLC"

if [[ "${LLLC_BOOTSTRAP_REINSTALL:-0}" == "1" ]]; then
  "$INSTALLER" install --reinstall >/dev/null
else
  "$INSTALLER" install >/dev/null
fi

BOOTSTRAP_BIN="$($INSTALLER path)"
[[ -x "$BOOTSTRAP_BIN" ]] || fail "resolved bootstrap binary is not executable: $BOOTSTRAP_BIN"
SELF_MAIN="$ROOT_DIR/lllcself/src/Main.lll"
[[ -f "$SELF_MAIN" ]] || fail "missing self main file: $SELF_MAIN"

tmp_root="$(mktemp -d)"
trap 'rm -rf "$tmp_root"' EXIT

main_file="$tmp_root/Smoke.lll"
cat > "$main_file" <<'SRC'
module Smoke

add(a Int)(b Int) Int = a + b
main() = add 2 3
SRC

run_capture() {
  local label="$1"
  shift
  local out_file="$tmp_root/cmd.out"
  echo "==> $label"
  if "$@" >"$out_file" 2>&1; then
    cat "$out_file"
  else
    cat "$out_file"
    fail "command failed: $label"
  fi
}

run_self_capture() {
  local label="$1"
  shift
  run_capture "$label" env LLLC_SELF_MAIN="$SELF_MAIN" "$LLLC" self "$@"
}

run_self_capture "check single file" check "$main_file"
grep -Eq '"ok":true' "$tmp_root/cmd.out" || fail "single-file check output mismatch"

run_self_capture "compile fs (single file)" compile --target fs "$main_file"
grep -Eq 'let add' "$tmp_root/cmd.out" || fail "single-file fs compile output mismatch"

run_self_capture "compile ts (single file)" compile --target ts "$main_file"
grep -Eq 'const add' "$tmp_root/cmd.out" || fail "single-file ts compile output mismatch"

ops_fixture="$ROOT_DIR/spec/examples/valid/26-operators-precedence.lll"
[[ -f "$ops_fixture" ]] || fail "missing operators fixture: $ops_fixture"
custom_binding_fixture="$ROOT_DIR/spec/examples/valid/29-custom-operator-binding.lll"
[[ -f "$custom_binding_fixture" ]] || fail "missing custom operator binding fixture: $custom_binding_fixture"

if rg -n 'isFixedSymbolicOp|lowerFixedSymbolicOp|op == "\|>"|op == ">>="|op == ">>"|op == "<\|>"' "$ROOT_DIR"/stdlib/src/Codegen*.lll; then
  fail "backend codegen still contains fixed symbolic operator lowering"
fi

check_no_raw_operator_tokens() {
  local file="$1"
  local target="$2"
  for token in " |> " " >>= " " >> " " <|> "; do
    if grep -Fq "$token" "$file"; then
      fail "raw operator token leaked in target $target output: '$token'"
    fi
  done
}

extract_generated_source() {
  local input="$1"
  local output="$2"
  awk 'p || /^\/\/ Generated by lllc/ { p=1; print }' "$input" >"$output"
  [[ -s "$output" ]] || fail "generated source marker not found in $input"
}

check_no_static_apply_tokens() {
  local file="$1"
  local target="$2"
  for token in "inc.apply(" "dbl.apply(" "toSome.apply(" "mixed.apply(" "llMaybeBind.apply(" "llMaybeThen.apply(" "llMaybeChoice.apply("; do
    if grep -Fq "$token" "$file"; then
      fail "$target emitted static/helper call through apply: $token"
    fi
  done
}

compile_generated_java_if_available() {
  local label="$1"
  local fixture="$2"
  local class_name="$3"
  if ! command -v javac >/dev/null 2>&1; then
    echo "skip javac gate for $label: javac not found"
    return 0
  fi
  if ! javac --release 21 -version >/dev/null 2>&1; then
    echo "skip javac gate for $label: javac --release 21 unavailable"
    return 0
  fi
  run_self_capture "compile java $label" compile --target java "$fixture"
  check_no_raw_operator_tokens "$tmp_root/cmd.out" "java/$label"
  check_no_static_apply_tokens "$tmp_root/cmd.out" "java/$label"
  local java_file="$tmp_root/$class_name.java"
  extract_generated_source "$tmp_root/cmd.out" "$java_file"
  javac --release 21 "$java_file" >/dev/null 2>&1 || fail "javac failed for $label"
}

compile_generated_cs_if_available() {
  local label="$1"
  local fixture="$2"
  local class_name="$3"
  if ! command -v dotnet >/dev/null 2>&1; then
    echo "skip dotnet gate for $label: dotnet not found"
    return 0
  fi
  local cs_dir="$tmp_root/cs-$class_name"
  mkdir -p "$cs_dir"
  run_self_capture "compile cs $label" compile --target cs "$fixture"
  check_no_raw_operator_tokens "$tmp_root/cmd.out" "cs/$label"
  check_no_static_apply_tokens "$tmp_root/cmd.out" "cs/$label"
  if grep -Fq "mixed(1L)(" "$tmp_root/cmd.out"; then
    fail "cs/$label emitted curried static invocation"
  fi
  extract_generated_source "$tmp_root/cmd.out" "$cs_dir/$class_name.cs"
  cat > "$cs_dir/$class_name.csproj" <<'CSPROJ'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
CSPROJ
  (cd "$cs_dir" && dotnet build -v:q --nologo >/dev/null 2>&1) || fail "dotnet build failed for $label"
}

for target in fs ts py java cs llvm; do
  run_self_capture "compile $target operators fixture" compile --target "$target" "$ops_fixture"
  check_no_raw_operator_tokens "$tmp_root/cmd.out" "$target"
done

pipe_fixture="$ROOT_DIR/spec/examples/valid/32-pipe-operator-binding.lll"
[[ -f "$pipe_fixture" ]] || fail "missing pipe normalization fixture: $pipe_fixture"
compile_generated_java_if_available "pipe fixture" "$pipe_fixture" "PipeAliasNormalization"
grep -Fq "return dbl(inc(2L));" "$tmp_root/cmd.out" || fail "java pipe fixture did not emit nested static calls"
compile_generated_java_if_available "operators fixture" "$ops_fixture" "OperatorsPrecedence"
compile_generated_cs_if_available "pipe fixture" "$pipe_fixture" "PipeAliasNormalization"
compile_generated_cs_if_available "operators fixture" "$ops_fixture" "OperatorsPrecedence"

check_custom_operator_binding_output() {
  local file="$1"
  local target="$2"
  if grep -Fq " %% " "$file"; then
    fail "raw custom operator token leaked in target $target output"
  fi
  grep -Fq "__ll_op_37_37" "$file" || fail "mangled custom operator name missing in target $target output"
  if grep -Fq "__ll_op_115_97_109_112_108_101" "$file"; then
    fail "normal identifier sample was mangled in target $target output"
  fi
  case "$target" in
    py)
      grep -Fq "__ll_op_37_37(2, 3)" "$file" || fail "python custom operator call did not lower to native function call"
      ;;
    java|cs)
      grep -Fq "__ll_op_37_37(2L, 3L)" "$file" || fail "$target custom operator call did not lower to native method call"
      ;;
  esac
}

for target in fs ts py java cs llvm; do
  run_self_capture "compile $target custom operator binding fixture" compile --target "$target" "$custom_binding_fixture"
  check_custom_operator_binding_output "$tmp_root/cmd.out" "$target"
done

project_name="sampleapp"
(
  cd "$tmp_root"
  run_capture "new project" "$LLLC" new "$project_name"
)
project_dir="$tmp_root/$project_name"
[[ -f "$project_dir/lll.toml" ]] || fail "new did not create lll.toml"
[[ -f "$project_dir/src/Main.lll" ]] || fail "new did not create src/Main.lll"

(
  cd "$project_dir"
  mkdir -p ../dep/src
  cat > ../dep/lll.toml <<'TOML'
[project]
name = "dep"
version = "0.1.0"
entry = "src/Main.lll"
TOML
  cat > ../dep/src/Main.lll <<'LLL'
module Dep.Main
val() = 1
LLL

  run_capture "mod add" "$LLLC" mod add dep=path:../dep
  grep -Eq 'Installed [0-9]+ dependencies into vendor/|\"ok\":true' "$tmp_root/cmd.out" || fail "mod add output mismatch"

  run_capture "mod why" "$LLLC" mod why dep
  grep -Eq 'dependency chain:|\"ok\":true|\"dep\"' "$tmp_root/cmd.out" || fail "mod why output mismatch"

  run_capture "mod tidy" "$LLLC" mod tidy
  grep -Eq 'Installed [0-9]+ dependencies into vendor/|\"ok\":true' "$tmp_root/cmd.out" || fail "mod tidy output mismatch"

  run_capture "install" "$LLLC" install
  grep -Eq 'Installed [0-9]+ dependencies into vendor/|\"ok\":true' "$tmp_root/cmd.out" || fail "install output mismatch"

  run_capture "check project" "$LLLC" check .
  grep -Eq 'Checked project|\"ok\":true|\"stage\":\"ok\"' "$tmp_root/cmd.out" || fail "project check output mismatch"

  run_capture "build project fs" "$LLLC" build --target fs .
  grep -Eq 'Built project|\"ok\":true' "$tmp_root/cmd.out" || fail "project build output mismatch"
  [[ -f "$project_dir/bin/fsharp/sampleapp.fsproj" || -f "$project_dir/bin/fsharp/sample.fsproj" || -f "$project_dir/bin/fsharp/sampleapp.fs" || -f "$project_dir/bin/fsharp/sample.fs" ]] || fail "project build artifacts missing"
)

python3 - "$LLLC" "$SELF_MAIN" "$ROOT_DIR" <<'PY'
import json
import os
import subprocess
import sys

lllc = sys.argv[1]
self_main = sys.argv[2]
root_dir = sys.argv[3]
env = os.environ.copy()
env["LLLC_SELF_MAIN"] = self_main
fixity_fixture = os.path.join(root_dir, "spec/examples/valid/27-fixity-decls.lll")
with open(fixity_fixture, "r", encoding="utf-8") as f:
    fixity_source = f.read()
custom_fixity_fixture = os.path.join(root_dir, "spec/examples/valid/28-custom-symbolic-fixity.lll")
with open(custom_fixity_fixture, "r", encoding="utf-8") as f:
    custom_fixity_source = f.read()
p = subprocess.Popen(
    [lllc, "mcp"],
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    text=True,
    env=env,
)

wire = "\n".join(
    [
        json.dumps({"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {"protocolVersion": "2025-03-26", "capabilities": {}, "clientInfo": {"name": "ci", "version": "1"}}}),
        json.dumps({"jsonrpc": "2.0", "method": "initialized", "params": {}}),
        json.dumps({"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}),
        json.dumps({"jsonrpc": "2.0", "id": 3, "method": "tools/call", "params": {"name": "ffi_inspect", "arguments": {"path": os.path.join(root_dir, "spec/examples/valid/23-external-opaque.lll")}}}),
        json.dumps({"jsonrpc": "2.0", "id": 4, "method": "tools/call", "params": {"name": "parse_source", "arguments": {"source": fixity_source}}}),
        json.dumps({"jsonrpc": "2.0", "id": 5, "method": "tools/call", "params": {"name": "parse_source", "arguments": {"source": custom_fixity_source}}}),
    ]
) + "\n"

stdout = ""
stderr = ""
try:
    stdout, stderr = p.communicate(wire, timeout=90)
except subprocess.TimeoutExpired as ex:
    p.kill()
    out, err = p.communicate()
    stdout = (ex.stdout or "") + (out or "")
    stderr = (ex.stderr or "") + (err or "")

ok_init = False
ok_tools = False
ok_ffi = False
ok_parse_fixity = False
ok_parse_custom_fixity = False
for line in stdout.splitlines():
    line = line.strip()
    if not line:
        continue
    try:
        obj = json.loads(line)
    except Exception:
        continue
    if obj.get("id") == 1 and "result" in obj:
        ok_init = True
    if obj.get("id") == 2 and "result" in obj and isinstance(obj["result"].get("tools"), list):
        ok_tools = True
    if obj.get("id") == 3 and "result" in obj:
        res = obj["result"]
        if (
            isinstance(res, dict)
            and res.get("ok") is True
            and isinstance(res.get("ffi_decls"), list)
            and int(res.get("external_count", 0)) >= 1
        ):
            ok_ffi = True
    if obj.get("id") == 4 and "result" in obj:
        res = obj["result"]
        if (
            isinstance(res, dict)
            and res.get("ok") is True
            and int(res.get("fixity_count", 0)) >= 1
            and isinstance(res.get("fixities"), list)
            and any(
                isinstance(fx, dict)
                and fx.get("assoc") == "infixl"
                and int(fx.get("precedence", -1)) == 6
                and fx.get("operator") == "+"
                for fx in res["fixities"]
            )
        ):
            ok_parse_fixity = True
    if obj.get("id") == 5 and "result" in obj:
        res = obj["result"]
        if (
            isinstance(res, dict)
            and res.get("ok") is True
            and int(res.get("fixity_count", 0)) >= 3
            and isinstance(res.get("fixities"), list)
            and any(
                isinstance(fx, dict)
                and fx.get("assoc") == "infixl"
                and int(fx.get("precedence", -1)) == 6
                and fx.get("operator") == "%%"
                for fx in res["fixities"]
            )
        ):
            ok_parse_custom_fixity = True
if not (ok_init and ok_tools and ok_ffi and ok_parse_fixity and ok_parse_custom_fixity):
    if stdout.strip():
        print(stdout, file=sys.stderr)
    if stderr.strip():
        print(stderr, file=sys.stderr)
    raise SystemExit("MCP handshake/tools-list/ffi-inspect/parse-source-fixity failed")
PY

echo "check-selfhost-e2e: OK"
